---
title: "Aberbach 1977"
date: "2024-03-22 18:31:34"
---

::: {.callout-note}
Created on: {{< meta date >}}

Last Modified on: {{< meta date-modified >}}
:::


## Citation

Aberbach, Joel D. 1977. “Power Consciousness: A Comparative Analysis.” The American Political Science Review 71(4): 1544–60. doi:[10.2307/1961495](https://doi.org/10.2307/1961495).


## Summary


## Notes

Originally created: 2024-03-22 18:31:34
Modified: 2024-03-22 18:37:15 -0400


Power Consciousness: A Profile



> "The major dependent variable in this study, the power consciousness indicator, is derived from answers to two very simple questions: (1) "Do you think people like you have too little political power, or just about the right amount?"; and (2) if the respondent replies "too little political power," "Why do you have too little power?"[n17] "


> "[n17] A follow-up question was asked only of those who felt they had too little power because of my fear that a probe of the answer "the right amount of power" would appear to challenge that response, damage the rapport between interviewer and interviewee, and bias other responses. The spontaneous comments given to our interviewers, however, and a follow-up question asked of those saying "right amount" on a survey administered to a small sample in Detroit, lead me to believe that these dangers are minimal. The question on the small Detroit study, incidentally, yielded answers focusing mainly on the existence of the franchise, other possibilities for participation, and general system satisfaction. My thanks to Professor Monica Blumenthal of the Survey Research Center at the University of Michigan for placing the item on her questionnaire."

>  "The phrase "people like you" in the lead-in question is meant to stimulate respondents, in Converse's words, to think of their "location in the capability pecking order."[n18] They should be stimulated to think of themselves as having a relative location, along with others, in the power order of the political system. The intention is to minimize any idiosyncratic explanations which focus on individual inadequacies as the source"

> "[n18] Converse, "Change in the American Electorate," p.335."




