---
title: "analysis-of-items-from-2023-09-25"
date: "2025-08-19"
---

:::{.callout-note}
The following is something I wrote dated 2023-09-25. I was analyzing the items themselves, which upon review, seems worthwhile to repeat.
:::

The question wording for survey items measuring external efficacy have always been very poorly worded. The general intent of the two survey items is to capture attitudes concerning 1) whether people feel that they can influence what the government does (i.e., NOSAY), and 2) whether the government appears to care about what the people say (i.e., NOCARE). The two items are thought to induce responses indicative of the same underlying attitude concept, but the evidence is not convincing in that regard nor do the survey items themselves present a logically valid link to that concept in theory.

"People like me don't have any say about what the government does." [NOSAY]

The first item, NOSAY, attempts to assess the extent a person believes that "people like me" do determine or influence the decisions and behavior of government. Note that this doesn't assess the belief on whether or not they *can* do so, as each response implies a presumption of capability except for "strongly agree"; each other response option (on a 5 or 7 point Likert scale) implies a particular degree of belief about efficacy to determine or influence government action. One issue, however, may concern the ambiguity implicit in what "have a say" conveys to the respondent. "Having a say" in what government does may be interpreted as "determining" what government does, whereas it appears that researchers most often want to know whether people believe they have any *influence* over what *government officials* decide to do. Thus, as a first step it appears important to clarify the specific end that political activity is intended to bring about before attempting to assess perceptions of efficacy in doing so.

That being said, however, if "having a say" means anything, it means having a particular degree of power to determine the final decision or choice present before the actors who are, indeed, empowered to decide. Hence the phrase, "not if I have anything to say about it" conveys the message that something will or won't happen or occur so long as I have power to determine or block its occurrence.

"I don't think public officials care much what people like me think." [NOCARE]

The second of the two items intended to measure external efficacy is more concerned with perceptions of influence on public officials. However this may not be conveyed well to the respondent. In order to evaluate whether or not, and how much, public officials care, a respondent may rely on their impression of congruence between public official behavior or expression and perceived public preferences. However, the largest potential confounder concerns the inclusion of "people like me" in the wording of the survey item. Rather than report their judgement of congruence between public official expression or behavior with public preferences or majority opinion, the survey item has the respondent attend to public official congruence with "people like me". In fact, this wording potentially imposes response effects related to whatever group is conjured up in reference to "people like me" in both survey measurement items for external efficacy.

Perceptions of responsiveness have been shown to be sensitive to the reference group in question [@esaiasson2015]. Just as well, judgements of efficacy may be sensitive to whatever group is conjured up in reference to the "people like me" phrase. The extent to which "people like me" are capable of influencing government behavior may be impacted by whatever group "people like me" refers to for each individual respondent. As a result, findings may reflect who the respondent feels is served better by government rather than the extent to which they judge the people capable of producing a response or determining the outcome.

As Esaiasson and colleagues assert [-@esaiasson2015] the measures of external efficacy capture an individual's affect toward a broad and generalized reference object "the government" or "public officials". In other words, people draw upon whatever impressions and sentiments arise in reference to "the government" to judge responsiveness. Their concern was that the reference object in external efficacy measures is highly ambiguous and "affectively charged". Whereas *perception of responsiveness* refers to judgements of how well particular actors (i.e., representatives) perform three acts indicative of their responsiveness to citizens[^1]. @esaiasson2015 finds that external efficacy and perceived responsiveness are distinct concepts in light of the evidence showing that people's perceptions of responsiveness are sensitive to different reference objects. These authors do mention, however, that external efficacy indicators, "are a serviceable alternative for many analytical purposes" presumably in regard to "...the wider representative process" [-@esaiasson2015, 442].

[^1]: Those acts are to *listen* to citizens, to *explain* their actions to citizens, and to *adapt* their decisions and behavior to align with citizen sentiments.

It may not only be the fact that a person draws upon their affect for the broad reference group "the government", but also, or more importantly, those feelings of that group in relation to "people like me".

We know, generally, how partisanship influences these approval/disapproval ratings too; so it is also quite possible that partisanship may also influence external efficacy as well. @wolak2018 finds this to be the case when examining attitudes of external efficacy at the state level. Although Wolak's concern wasn't over the question wording of external efficacy items referring to "My government" and "people like me", the evidence showing the influence of partisanship in external efficacy measures may speak to the same point.

It may be assumed that the inclusion of "people like me" conjures up "ordinary people like me" or even "we the people" in the mind of the respondent, but supposing this is the case, then the question may only work to incline a negative response. Especially in a country where public sentiment has been suspicious of government *qua* traditional democratic 'spirit'--which essentially prescribes distrust of government. The notion that the government truly cares about what "we the people" think may go against commonplace ideations about the relationship between *the government* and *the people* writ large to a people who understand themselves as a democratic people. Therefore, we may expect a negative response for those respondents who regard "people like me" to mean "we the people". However, without including more question items designed to identify and distinguish which groups respondents think about when they read "people like me", we are left with no way to interpret patterns of negative or positive responses beyond conjecture.


In the first sense, the government is being evaluated for how well they *listen* to "people like me"; how *attentive* is government when "people like me" have some expression or knowable opinion. Presumably, the government is evaluated more positively when government officials are perceived to be more attentive to constituents, the public at large, or perhaps implicitly "people like me". In other words, the voices of "people like me" are judged to be more externally efficacious when government probes to ascertain what "people like me" have to say. Yet nothing connotes that "having a say" *determines* what the government actually does; it is simply implied that "having a say" should have an expected effect on government action. This suggests that there's no clear way to judge when the voices of "people like me" competently influence what the government does, leaving open the potential that participants derive judgement from their most accessible impressions of government or public officials. Presuming the participant approaches the survey item in this way, I would suspect that partisanship (at the very least) strongly influences response choice.

The second possible object of evaluation for the old version of the NOSAY survey item is the efficacy of *public expression*; when "people like me" say something, it will more or less affect what the government does. This approach evaluates the capacity to influence direction of government action by the modality of *public expression*, i.e., "having a say", on par with the other survey item NOCARE. It's unclear whether a participant would evaluate the effectiveness of "having a say" upon what the government does as though it were some form of activity itself.