---
title: "converse1972"
---


## Citation

Converse, Philip E. 1972. “Change in the American Electorate.” In The Human Meaning of Social Change, eds. Angus Campbell and Converse Phillip E. Russell Sage Foundation, 263–338.

::: {.callout-note}
This literature summary/review of Converse was dated as written on `2024-02-17`. 
:::



> "An alert, informed electorate has been considered vital to popular government, and the main path to such an electorate has been considered to be the extension and intensification of formal public education. If man-years spent in classrooms is any indicator of sophistication, then the American electorate is the most sophisticated in the world. among the large set of countries enjoying universal suffrage." [@converse1972, 323]
	

> "But the true domain of education as a predictor has to do with the large class of indicators of popular involvement and participation in politics. Whether one is dealing with cognitive matters such as level of factual information about politics or conceptual sophistication in its assessment; or such motivational matters as degree of attention paid to politics and emotional involvement in political affairs; or questions of actual behavior, such as engagement in any of a variety of political activities from party work to vote turnout itself: education is everywhere the universal solvent, and the relationship is always in the same direction. The higher the education, the greater the "good" values of the variable. The educated citizen is attentive, knowledgeable, and participatory, and the uneducated citizen is not." [@converse1972, 324]

> "As social science relationships go, these links between education and political involvement are uncommonly strong. By way of illustration, let us consider what has come to be seen as a central variable of a mediating sort where political participation is concerned." [@converse1972, 324-325]

> "We have treated this indicator under the name "'sense of political efficacy". Others have called it "sense of political competence," and still others have turned the variable on its head and labeled it "political alienation" (absence of a sense of political efficacy) . We have measured the notion with a small scale of four simple agree-disagree items, and this scale has been very widely borrowed." [@converse1972, 325]
	
> "The four items surviving from the original five-item scale are: 
* "I don't think public officials care much what people like me think";
* "Voting is the only way that people like me can have any say about how the government runs things";
* "People like me don't have any say about what the government does"; and
* "Sometimes politics and government are so complicated that a person like me can't really understand what's going on." 
		The first formal description of the measure, along with some discussion of its initial measurement properties, was provided in Angus Campbell, Gerald Gurin, and Warren Miller, *The Voter Decides*....It might be said that long work with the measure has left us well aware of its shortcomings, particularly in its sensitivity to acquiescent response set. See Campbell et al.. The American Voter, especially pp.515-519. We have, however, maintained the measure in its current form because of our strong interest in the kind of long-term trend analysis employed here." [@converse1972, 325, n79]
		
> "Others have developed variant measures, or have split the concept into diverse components. What is important is that the general notion itself has attracted such high interest, and tends to be seen in rather common terms: people differ markedly in the degree to which they feel confident about participating in politics and getting some meaningful response from "the system.'" [@converse1972, 325]
	
> "This variable became one of the central foci in the classic Almond-Verba "Five-Nation Study" of the quality of mass political participation, and it is of interest that this study rested very heavily on cross-national differences in levels of education as a prime explanatory term for cultural variation in citizen participation."
	
		Almond, Gabriel Abraham, and Sidney Verba. 1963. The Civic Culture; Political Attitudes and Democracy in Five Nations, an Analytic Study. Princeton, NJ: Princeton University Press.
		
> "Moreover, it is noteworthy that a more generic concept, but one which is closely related, has turned out to be something of a "sleeper" variable in a much wider range of social research. This indicator has been variously called "sense of personal competence," "ego strength," or, turned on its head, "fatalism." Thus, for example, the Coleman report on racial segregation of schooling discovered to the surprise of the investigators that a measure of personal sense of competence turned out to be the best predictor of child performance in schools, outstripping a very wide variety of other structural, relational, and psychological factors."
	
> "It is not surprising that political efficacy turns out to be strongly related to measures of personal competence, since it seems a specific manifestation of such a syndrome. And both of these entities are in turn closely related to level of education." [@converse1972, 325-326]

It is interesting how, here, Converse is really the only one distinguishing between political efficacy and personal competence in the way that he is, while also not being so explicit about the distinction. Perhaps because of his relation to the team who brought about the concept and initial measurement. Though he does seem allured by the notion that, beneath the simple concept, a personal sense of confidence, strong ego, and competence drives much of the findings. The relation to education speaks to one's personal feelings of competence, and thus, efficacy. But he still says that political efficacy only turns out to be strongly related to measures of personal competence--not that they are one in the same. I wonder, then, if the unstated or unwritten theoretical foundation of the concept also seemed fleeting to him in light of the evidence.

> "In short, then, all the ingredients are present for a demonstration that the level of political efficacy and, with it, the quality of electoral participation in the United States, is advancing on a mounting tide of educational advantage. People of college background are much more efficacious politically than others, and the proportion of people with college exposure in the electorate has about doubled in the last 16 years alone." [@converse1972, 326]

> "Yet, these are mere static correlations and cannot in themselves ensure that we are dealing with dynamic or causal ones. Even the Almond-Verba work rests on synchronic comparisons between societies rather than diachronic measurement. Counter-models in some variety can be imagined, Formal education may develop the capacity to read or some understanding of the calculus but is political efficacy dispensed by the educational system in anything like the same way?" [@converse1972, 326]

> "Let us argue for the moment that progress through an educational system contributes absolutely nothing to enhancement of an individual's sense of political efficacy. Instead, let us see this efficacy as some residue of the individual's interactions with other actors and institutions in the political domain over time, a summary expression to be blunt, of how often he "wins" and "loses." *There is a natural pecking order in societies, we might argue, which arises from a variety of individual traits and determines the ratio of wins to losses, including success at completing an education. The well-educated in modern societies are, on balance, the winners in such transactions, and the poorly-educated are the losers.* Hence, there is naturally a strong static correlation between education and sense of political efficacy, although if there were no formal educational process at all, individuals would still differ in about the same degree in their fell capacity to participate effectively in the political system." [@converse1972, 326, emphasis added]

This so strongly indicates the implicit beliefs inherent in Converse's thinking. Although he is setting up more of an argument position from which to reference expectations, the idea of the "natural pecking order" that arises from a variety of naturally-endowed individual traits is deeply embedded in his thoughts as well as the thoughts of scholars then, now, and dare I say, always. That is, the model of the efficacious citizen is not merely an conceptually valid model in the abstract but an ideal prototype molded to resemble the way scholars imagine themselves as sophisticates. Thus, this is from whence our conception of political efficacy has so derived; the progeny of the honeymoon era between psychoanalysis and public opinion research in political science is this abstract and ever implicit model of the engaged, efficacious, interested, and educated citizen. It is interesting to note how the same degree of "natural aristocracy" is present here as it is in early writings by Madison in regard to the general public. For the founders saw themselves as those of which who were suitably well-equipped to rise 'naturally' from the constituency as better and recognized for it. Here too, we see the implied markings of the same status reserved for those who are 'naturally' equipped to win more than lose, and in this case, complete an education. 

Funny that, as Converse wrote this analysis of the longitudinal data, racial segregation was still such a focal issue and practice despite its unconstitutional status, women were unable to open bank accounts or divorce their husbands without sufficient grounds limited by the state, miscegenation laws had only recently been overturned by the Supreme Court in 1967 (just five years prior to the year of this publication), and deferment of conscription during the Vietnam war was commonly extended to students of middle- and upper-class White Americans. The draft only terminated in 1972. So despite Converse's notions of there being a "natural pecking order", it is not nor was not an individual's traits which inclined their success at completing an education. 

It seems that he's really questioning why political efficacy correlates with education so starkly. Converse falls back into the comfort of resting the theory upon individual differences--on personality traits and characteristics. He begins to say next that education merely correlates but is not then necessitated as a cause for political efficacy. He carries on to say that people would still differ in political efficacy in the same way even if no formal education processes existed, except this counter-factual assertion has no basis except his assertion of it. The interesting thing is that Converse is arguing here---not wondering, and not curious. There's something bothersome to him, it seems, about the correlations he sees in the data he cites and presents. His hypothetical argument about the pecking order of educated winners and dumb losers may speak to something deeper. The table of 1966 data he presents (p.326) shows that increasing levels of education correlates with less agreement with the statement "I don't think public officials care much about what people like me think". So higher educated individuals do display higher sense of political efficacy, driven perhaps by "stronger egos" and high sense of personal confidence. Maybe he is questioning the suggestive interpretation of the correlation as a good scientist would; regression may work better to show whether education engenders political efficacy. Or maybe the data seems to suggest the higher educated view themselves as elites who find little to no fault in the system as is.

> "If we accept this model. then we encompass the static fact that education relates strongly to efficacy, but we do not expect that increasing levels of education lead over time to any particular change in aggregate levels of efficacy." [@converse1972, 326]

> "On the face of it, most people would expect the truth to lie somewhere between the "education-driven" model and this latter model which rests on an assumption of a relative pecking order, That is, we would expect education to make some instrumental contribution to efficacy, in part because of demonstrations like the Almond-Verba cross-national comparisons, which belie any model of efficacy levels as a universal constant within societies across space and time. On the other hand, most would suspect that there is some adulteration of education effects as the upper levels of education recruit more and more widely in the population." [@converse1972, 327]

> "What is attractive about these two simplistic models is that each produces an exact prediction as to how our efficacy data should behave over time. Although details vary somewhat by item, for example, the education-driven model would require that other things equal, our efficacy measures should have forged upward by about 5 or 6 percent nationally between 1952 and 1968, with efficacy levels within education classes resting constant over this time. The pecking-order model would predict constant levels of efficacy over this period, with declining levels of efficacy visible within specified education categories. Moreover, if other things could be taken as equal, one might be willing to see any intermediate level of gain in efficacy falling between 0 percent and 5 or 6 percent as a reflection of the relative weight of the two models, which would be an extremely interesting specification in itself and one which would be helpful in long-range predictions about efficacy change." (327)
	
What he is saying is, that the simplistic education-driven model explaining political efficacy suggests that we should see certain gain in political efficacy as more of the national population becomes better educated. Whereas the "pecking-order" model would predict constant levels over the same period, with political efficacy levels dropping as more people enter into higher levels of education; more people, less special status to the "winners". Taking the relative weights of the models together might allow us to predict political efficacy quite well.

While it is smart, its quaint. Converse, like others, assumes the political system is stable and perfectly facilitates the capacities of the citizenry to effectuate their political aims. He assumes, said otherwise, that the only limitations regard the individual's perceived and actual capacities as afforded by their education or social status, which is in turn inclined by particular individual dispositions. 

Following this thinking by Converse, he quickly accounts for the fact that the performance of the political efficacy items over the years are insufficient to confirm either the education-driven model or the pecking-order one. He seems to take into account that people lead social lives and that events in society as well as the related political issues are likely to influence the individual's sense of political efficacy. He hints that there may be "…some underlying syndrome of efficacy for which these items are adequate indicators" (327). 

> "The one item departing from this pattern by its persistent and uneven upward movement is the one which proposes that "voting is the only way" to have an impact on government. The performance of this item is not surprising in context. Developments of the 1960's were marked by a great expansion of forms of political participation associated primarily with the civil rights movement and resistance to the Vietnam War, Sit-ins, demonstrations, marches, and various more or less violent disruptions came to be a common recourse for dissent, as means of exerting grass-roots influence on government beyond voting alone." [@converse1972, 328]

> "At first we assumed that, because of civil rights innovations, the upsurge in the belief that there are other ways of exerting influence [other than] voting would be concentrated among blacks. But examination showed that whereas blacks had contributed their share or more to the faint rise in these beliefs from 1952 to 1964, the bulk of the rapid upturn after that date came among whites both North and South." 

> "Further analysis has succeeded in clarifying what is going on here, however. The lowest educational levels have shown little or no gain in perceptions of other ways to influence government over the whole period from 1952 through 1968. At each higher educational category, however, the gain in these perceptions increases. Thus, for people who have not completed grade school, the gain has been on balance less than l percent in 16 years. For those who have completed grade school, the gain is nearly 5 percent. The progression continues quite regularly to those who have completed college, where the gain is of the order of 30 percent!" (328)

So Converse comes to find that there definitely was a linear upsurge in political efficacy in one of the original survey items from the original political efficacy measure, but it wasn't clear why because it differed remarkably from the other four items. The item in question was "Voting is the only way that people like me can have any say about how the government runs things.", to where disagreement indicated a higher sense of political efficacy. The rest of the items seem to drop steady but erratically in comparison to this one item over time. As Converse says, the 1960s were pretty crazy. Yet what seems to actually explain the steady incline of this one survey item has to do with education after all. More specifically, it appears that with increase in education level, people seem to gain some enlightened perception on other ways to influence government beyond just voting. Only the lower educated see voting as the only means to influence the political process, and this seems to explain their associated lower levels of political efficacy.

> "Given the fact that many of the new forms of political participation have been spawned and most heavily practiced on college campuses, it is not surprising that cognizance of them should be most strongly registered among persons closer to college milieu, with a diminishing "trickle-down" effect to lower levels of education, where "people like me" have little participation in such affairs."

> "Several morals, both substantive and methodological, can be drawn from these simple materials. This is an interesting case, for example, of a scale deemed unidimensional by Guttman criteria in 1952, one component of which has pulled out of line rather markedly in response to phenotypic events in a subsequent period. Our analysis of these trends would have been greatly muddied if we had proceeded with the composite scale taken as a whole."

We would have been blind to this trend had we deemed political efficacy to be unidimensional. When one reads the discussion of the survey items and measurement of political efficacy from "The Voter Decides", it does appear very odd that one item was dropped only for the sake of increased measurement validity. Analysis of the survey items themselves might reveal that 'one of these things is not like the others', or at least it did to me. In fact, in writing about it initially, I found it to be the most ironic that it was dropped from the measure of political efficacy, explained in the book "The Voter Decides", as it was the only item that asked the respondent to consider whether the voter decides. Yet decades later, Converse is there writing about how interesting it is that the one deviant survey item happened to capture something more true to the conceptual idea than the other measurement items.  

	From my original notes: Of all the survey items included in the scale to measure sense of political efficacy, the only item that asks respondents to agree or disagree with whether "the voters decide" was dropped (mainly) due to having too large of an error percentage. The item is essentially paraphrase of the statement, "the voters decide how the country is governed", and considering the title of the book, the decision to drop the item is terribly ironic. What this has to do with political efficacy seems all too conceptually important to be dropped from the scale, and calls into question whether the other items validly capture the construct as well.

> "More important is the substantive message conveyed by the other three items, The fact that they move rather nicely in tandem suggests that it remains reasonable to think in terms of some generic sense of political efficacy which these items tap. This suspicion is reinforced by analyses showing that, unlike the situation with the voting item, the depression in efficacy of the 1960's was shared more or less across all categories of education. This is not to say that divergences from parallel trends between educational groups fail to appear on other items. There arc some such divergences, of a minor but systematic sort. "

> "For example, the item suggesting that politics is too complicated to understand is the most purely cognitive of the efficacy items and reflects more on the person agreeing with it than it does upon flaws in the political system. When agreement with this item increases in the 1960's (declining efficacy) , the upswing is somewhat stronger among people of lower education. In other words, when political events seem chaotic to the observer, he is more likely to attribute it to his own inferiorities if he is of limited education; the well-educated observer tends instead to assign the difficulty to the responsiveness of the system. While styles vary mildly in these ways, the decline of "efficacy" registers in both groups, however, and in reaction to more or less common events." (329-330)

Yet therein lies the problematic assumption I contend with; Converse assumes that the well-educated observers aren't deriving judgement from their own self-confidence and feelings of personal political competence. Somehow because the lower educated show more of an increase in feeling that "politics is too complicated to understand", this means that the higher educated are more sensitive and better equipped to recognize that chaos in political affairs doesn't impact their ability to impact the political process or influence government actors. I don't know how Converse comes to this interpretation other than by strong assumptions of the political system itself--the better educated know better and, thus, are less perturbed by chaos in politics because they understand that their ability to change or control the political process is unperturbed. 

Not in the external efficacy measurement items, nor the internal, nor even the original political efficacy items. None of the items in practically all of the measures of political efficacy have the respondent evaluate the capacities afforded by the political system for the people to produce responsive government. In almost every single survey instrument to measure political efficacy, the individual respondent judges the capacity of individual political activity to impact the political process by examining their own personal competence and awareness or the extent to which they feel that the government is responsive to "people like me". And even if the survey respondent doesn't focus on their own personal political abilities to make a judgement on the capacity to do politics effectively, survey items have them focus instead the competence of people more generally but still reference some particular group or collective (e.g., Lee's measure of collective efficacy making direct reference to "the Hong Kong people").

IRONICALLY The government was more responsive in the 1960s, but hardly. The achievements of the 60s are attributed to the long and hard fights from civil rights leaders, but it required a government sensitive to such endeavors after centuries of oppression. Had there been, say, proportional representation in the United States at that time, could we say that the government would have been as responsive to a disproportionately small minority party of newly engaged Black citizens? Could we say the government would have been as responsive without the electoral connection provisioned by the two party doom loop? Maybe a coalition would have formed to where racial and ethnic minorities were able to mobilize enough political power in government to bring about the civil rights era in much the same way, but it feels doubtful considering that half of the electorate was completely racist while the other half was mostly indifferent. Those calling for an end to Vietnam would find themselves utterly powerless to stop the war machine. 

> "It is appropriate to call the efficacy change in the 1960's one of "disenchantment" both because there is a strong affective component in the items used as indicators. ( evaluation of government responsiveness ) , and because the aggregate drop in efficacy has been too large and rapid to be accounted for by any influx of young people alienated from government. It must have involved an actual constriction at the individual level of many persons' feelings of political efficacy." [@converse1972, 330]

> "Most important conceptually is the juxtaposition of declining efficacy with aggregate levels of political interest that have at the very least been maintained, and probably have risen."  [@converse1972, 332]

> "To summarize, then, indicators of political attentiveness and activism appear to have edged forward over the past two decades in something like the measure that advances in education, with which all are closely correlated, would lead one to expect. And these trends stand in rather marked contrast to the evolution of feelings of political efficacy in the population. Efficacy has been accorded central theoretical importance in the field and, in general, is more strongly correlated with education than any of the other terms, yet it has shown a marked regression during the middle 1960's." [@converse1972, 334]

> "As implied at several points. it is useful conceptually to partition gross feelings of political efficacy as we have measured them over the years into at least two components, which might he more precisely labeled "personal feelings of political competence" and "trust in system responsiveness." The first term refers to the individual's sense of his own fundamental capacities and experience in operating in a political domain. The second refers to perception of properties of the political system as it stands at a point in time. The distinction is essentially the same as one made by Gamson between "efficacy" and "trust"" [@converse1972, 334].

		> ^87 William A. Gamson, Power and Discontent. Dorsey, Homewood, IU., 1968, pp. 39-48. Others, such as Almond and Verba, have made somewhat parallel distinctions,

Here's an excerpt of what Gamson said. 
		> "The concept of political alienation is broader than the trust dimension and Almond and Verba suggest the difference in their distinction between input and output alienation. Political alienation includes both an efficacy (or input) dimension and a trust (or output) dimension. Work on a sense of political efficacy derives from the studies by Campbell and his colleagues (1954; 1960; 1966). Political efficacy is measured by disagreement with such items as ‘‘People like me don’t have any say about what the government does,” and “Voting is the only way people like me can have any say about how the government runs things.” The efficacy dimension of political alienation refers to people’s perception of their ability to influence; the trust dimension refers to their perception of the necessity for influence. Feelings of low efficacy and feelings that the government is not being run in one’s interest are, of course, likely to be found together. If one feels he cannot contribute significant inputs he is likely also to feel unhappy with the outputs but this is an empirical hypothesis which might prove false under some conditions (e.g., paternalism, noblesse oblige). In any event, these two aspects of political alienation can be conceptually distinguished and the trust dimension refers to beliefs about the outputs of the political system." [@gamson1968, 42]	

Again, supporting the idea that political efficacy is multidimensional, though in this case, efficacy is contrasted with trust. The notion of the "input and output" dimensions is slightly different than the distinction made by Lane in 1959 and Converse here in 1972 between one's personal feelings of competence and trust in system responsiveness. Converse glosses over any nuance by saying the distinctions are "essentially the same", but it seems just a bit too different when considering the discussion by Gamson. 

Trust and efficacy are distinct concepts, but so long as I have no choice but to trust your decisions and behavior, than I cannot say I feel efficacious enough to determine them. At best, I may believe that I have the capacity to influence your choices and behaviors. However that is not a sense of control over the responsiveness of the system, it is the extent to which I feel I can influence your decisions and behaviors. This brings us all the way back around to the aim of political participation. 

The fact that I am not in control of the outcomes, but you are, and the fact that our relationship is one of principal and agent, then my trust isn't that the outcomes are favorable to me. Rather, I must trust that I determine the outcomes through you. Because I trust that you'll produce outcomes by my direction and influence, then you are what makes me feel like I have the capacity to bring about political outcomes and results. Yet this is merely a feeling contingent on positive perception of my ability to determine your decisions and behaviors. Should I become aware that I, in fact, have no real ability to determine your actions, then I would not have a sense of external efficacy. Yet under strong assumptions of the way the system works, or perhaps uncritical faith in the system itself, I may not come to feel only that you are less responsive than you should be. So long as my perception of government responsiveness is sufficiently satisfied, then I will feel externally efficacious. Therefore, the confusion of concepts like external efficacy, trust, and government responsiveness confounds both the theoretical foundation of the concept and the measurement of them all. External efficacy isn't conceptually valid as a distinct independent concept nor as a twin dimension contrast with internal political efficacy. 

Gamson isn't discussing two dimensions here, he's discussing only one, and it's the one usually referencing external efficacy. Converse mistakenly distinguishes efficacy and trust for internal efficacy and external efficacy, respectfully, but Gamson is only discussing efficacy in the external sense of the word. 

It seems clear to me that trust and efficacy are mistakenly referred to as distinct when discussed here by Gamson. It is not that they are two dimensions, it is that Gamson is referring only to one but using two words. Gamson highlights one important point, "High trust in authorities implies some lack of necessity for influencing them." (46-47). 

As it has been conceptualized over the years, and as measurement instruments have been refined to capture one's internal sense of political efficacy, defined as some personal degree of self-confidence in one's own political competence and awareness. The twin dimension, however, isn't very well conceived and conceptually confused with a variety of related concepts such as government responsiveness and trust in government.


