---
title: "craig1979"
date: "2024-08-26, 09:23:26"
---

::: {.callout-note}
Created on: {{< meta date >}}

Last Modified on: {{< meta date-modified >}}
:::


## Citation

Craig, Stephen C. 1979. “Efficacy, Trust, and Political Behavior: An Attempt to Resolve a Lingering Conceptual Dilemma.” American Politics Quarterly 7(2): 225–39. doi:[10.1177/1532673X7900700207](https://doi.org/10.1177/1532673X7900700207).


## Summary




## Notes

The abstract:

> "Political efficacy and political trust are concepts which have become central to the study of political behavior, yet different studies continue to conceptualize and operationalize these variables in different ways. This study builds upon previous research in an attempt to clarify our understanding of the dimensions of political efficacy and their relationship to political trust. Evidence from three independent samples suggests that "input efficacy" and "output efficacy" are distinct attitudinal dimensions, that each is related in different ways to political trust, and that each may help us to better understand the psychological bases of  political action." [@craig1979, 225]

> "While much of the literature involving efficacy and trust is  relatively insensitive to questions of dimensionality, recent  studies have been more attentive to this issue. For example,  Converse (1972: 334) has acknowledged that the SRC efficacy scale seems to contain both personal and institutional components similar to those noted above. Balch ( 1974) demonstrated  that this scale breaks down into two pairs of items, each relatively  uncorrelated with the other." [@craig1979, 226]

> "These are internal efficacy (SRC  items 2 and 4), i.e., the individual’s belief that means of influence  are available to him, his evaluation of his own political abilities,  and external efficacy (SRC items 1 and 3), i.e., the belief that the  authorities or regime are responsive to influence attempts." [@craig1979, 226]

Note: I've written an extensive comment on this in another journal entry dated 2024-08-22. I'll copy it here as well.

Of all the early studies into political efficacy, this one is the most suspect. The conceptual distinctions are not really coherent, the measurement items listed come off like a first draft attempt at devising a measurement instrument that fits distinctions made in previous literature, the conceptual distinctions appear to me developed post-hoc, and more. It seems like a load of questions were thrown at two student samples, and then where a larger test of the items on a national sample would be was replaced by a substantially weaker, hardly permissible, test of the conceptual dimensions using the 1979 CPS national elections study.

> “Balch ( 1974) demonstrated that this scale breaks down into two pairs of items, each relatively uncorrelated with the other. These are internal efficacy (SRC items 2 and 4), i.e., the individual’s belief that means of influence are available to him, his evaluation of his own political abilities, and external efficacy (SRC items 1 and 3), i.e., the belief that the authorities or regime are responsive to influence attempts.” [@craig1979, 227]

This one is important. The belief that the "*means of influence* are available to him" is conjoined with "his evaluation of his own political abilities".

This is and has been one of the staple key points of my consternation with the concept overall. The "means of influence" are juxtaposed with the individual's personal abilities, and thus, when a person appraises their internal political efficacy, they appraise the means of influence available within themselves. In other words, they make an impressionistic judgment of their own political capacities to "know" and "participate effectively"; Whereas "participate effectively" means "successfully influence government outcomes or the decisions or behavior of government officials. The assumption laden throughout the literature that government outcomes, responsive government, is merited by the competence of citizens --i.e., those subject to governance. 

This assumption implies a predicate assumption about the political system itself, which is that the system is fully and uniformly conducive to the means of influence available to the population. The predicate assumption is unobjectionable only insofar as *influencing* government or government officials is not equated with *production* of political outcomes. That is to say, so long as the *capacity to influence* is not conflated with the *capacity to shape political conditions*.

::: {.callout-note}
## NOTE on 2024-08-26
The point I'm trying to make is that the implication that "responsive government" or simply "good government" is merited by the competence of the citizenry is predicated by the assumption that the goal/end of political participation is merely to influence government rather than to shape/control political conditions. The predicate assumption equivocates or conflates the goal "to influence" government as the same as shaping the state, and my argument is that such an assumption is invalid. The predicate assumption is objectionable insofar as *influencing* government or government officials is equated or conflated with the end of political participation.
:::

Yet, in this and every conceptual definition of political efficacy, *influencing* government officials is established as the end (purpose, aim) of political participation. As such, voting is not *a means of political production* but a form of political expression. Likewise, political expression is elevated as participatory political activity. What this means is that the maximum effect of political participation has been conflated, and thus limited, with the maximum effect of public opinion. Due to this conceptual limitation put in place by scholars and students of politics, actions can speak no louder than words.

To put in other words, the assumption is that the political system equally facilitates and is conducive to political expression as though such expression carries the authoritative force of governing actors. Thus, democratic government is characterized as responsive government, and responsive government is produced by those who participate in the political process. When government---officials, institutions, or policy---is deemed unresponsive to public demand (or needs), the remedy is to increase popular participation under the assumption that political participation serves as the people's means of political production. However, political expression is considered political participation---which both conflates expressive acts as a means of political production and reduces the maximum effect of purpose-driven political action down to the maximum effect of those expressive acts. Which is to say, the efficacy of political participation is reduced to the efficacy of public opinion.

The explanation for an unresponsive government is, therefore, presented as the people's general inability *to influence government into responsiveness*. Simply put: the system works, so it's the people's fault. Under the assumption that the means available to the people are sufficiently adequate for producing responsive government, fault rests entirely on the people---in particular, some indefinite degree of political competence. 

The politically competent citizen is the one who recognizes, and by expressive engagement actualizes, the extent of their political capacity. Those who believe in themselves *politically* are high in internal political efficacy; those who find government responsive to citizen demands are high in external political efficacy. Therefore, the person who believes in their own political competence and believes the government is responsive is high in their overall sense of political efficacy.


> "Each  pair appears to relate differently to various dimensions of political participation (interest, knowledge, and propensity to participate) ; further, the two pairs have rather sharply distinct relationships with political trust and propensity toward political protest." [@craig1979, 227]




> "The need for conceptual clarification is reaffirmed by evidence  which points to differing patterns of attitudinal change over time,  at least in the American context. Converse (1972) documented an  irregular aggregate increase in the personal effectiveness component over the period 1952-1968-an increase generally consistent with rising educational levels in the electorate." [@craig1979, 227]


> "The responsiveness component, on the other hand, began an aggregate decline during the 1960s as citizens became increasingly  likely to perceive the government as beyond their sphere of influence." [@craig1979, 227-228]

> "The result of these and other deliberations has been a proliferation of attitudinal constructs, each intended to tap one or another element of the broader concepts of efficacy and trust. Even limiting ourselves to the general themes just reviewed, we can identify at least four separate ideas in the literature:

1.    *personal effectiveness*---a belief that one is generally the master of his environment and able to bring about preferred outcomes in  his daily life; 

2.    *political effectiveness*---a belief that one is personally effective in the political sphere; 

3.    *institutional responsiveness*---a belief that authorities will be responsive to the influence attempts of citizens generally (in addition to or in place of one’s individual efforts); and

4.    *institutional benevolence*---a belief that authorities will be responsive to the needs of citizens (apart from any consideration of  citizen demands)."

The thing I notice from this short list is that "political effectiveness" is not defined on par with the others. Embedded within 'political effectiveness' is 'personal effectiveness', the only distinction is that 'political effectiveness' concerns the political sphere, whereas personal effectiveness apparently does not. What is vague is the undefined "political sphere". 

If we simply use the definition of 'personal effectiveness' for 'political effectiveness', then we get the same thing, i.e., a belief that one is generally a master of the political sphere and able to bring about preferred outcomes in political life. In all of these definitions, the focal agent is the individual person---so it is a belief about capacities of the self. Because of this, it is untenable that 'political effectiveness' refers to a belief an individual has about themselves as the "master" of the political sphere and capable of personally bringing about political outcomes. 

Once the focal agent is no longer the individual, but the polity *en mass*, then the definition doesn't appear to be nearly as problematic. However, we must consider what "master" implies, especially in the context of the entire polity. Since effectiveness is qualified by 'mastering' the environment, this would entail the capacity to shape or control the political environment in accordance to the polity's preferences or needs. However, given the plurality of interests, the capacity is limited to shaping the political environment according to the needs and preferences of the polity *held in common*[^1]. For the entire polity to be considered the "master" of the political environment, no one person or smaller subset of the polity could reign as master of the political environment the political environment, but rather the society would need to be "masterless" such that the polity as a whole reigns by their capacity to shape the political environment. Additionally, 

[^1]: This is contrast to shaping the environment in accordance with the needs or preferences of a majority of the polity, which would indubitably exclude needs or preferences of a minority. Given that a majority is simply more than half of the whole, then the exclusion of minority interests could potentially consist of one-less than half of the polity. Such an approach simply renders a majority of the polity as a fickle master of the political environment.      

Accordingly, political effectiveness, or rather, political efficacy best refers to a belief that the polity is capable of shaping the political environment in accordance with the needs or preferences held in common (contra. majority) 



## 2025-08-06

:::{.callout-note}
I wanted to include this note from Zotero about this paper here, even though I see a lot of the above was probably written in tandem.
:::

Of all the early studies into political efficacy, this one is the most suspect. The conceptual distinctions are not really coherent, the measurement items listed come off like a first draft attempt at devising a measurement instrument that fits distinctions made in previous literature, the conceptual distinctions appear to me developed post-hoc, and more. It seems like a load of questions were thrown at two student samples, and then where a larger test of the items on a national sample would be was replaced by a substantially weaker, hardly permissible, test  of the conceptual dimensions using the 1979 CPS national elections study.

“Balch ( 1974) demonstrated that this scale breaks down into two pairs of items, each relatively uncorrelated with the other. These are internal efficacy (SRC items 2 and 4), i.e., the individual’s belief that means of influence are available to him, his evaluation of his own political abilities, and external efficacy (SRC items 1 and 3), i.e., the belief that the authorities or regime are responsive to influence attempts.” ([Craig, 1979, p. 227](zotero://select/library/items/93JVZMML)) ([pdf](zotero://open-pdf/library/items/L5PSZT6L?page=3))

This one is important, the belief that the "means of influence are available to him" is conjoined with "his evaluation of his own political abilities".  
This is and has been one of the staple key points of my consternation with the concept overall. The "means of influence" are juxtaposed with the individual's personal abilities, and thus, when a person appraises their internal political efficacy, they appraise the means of influence available within themselves. In other words, they make an impressionistic judgment of their own political capacities to "know" and "participate effectively". Whereas "participate effectively" means "successfully influence government outcomes or the decisions or behavior of government officials". The assumption is laden throughout the literature that government outcomes, responsive government, is merited by the competence of citizens \--i.e., those subject to governance.

“Each pair appears to relate differently to various dimensions of political participation (interest, knowledge, and propensity to participate) ;” ([Craig, 1979, p. 227](zotero://select/library/items/93JVZMML)) ([pdf](zotero://open-pdf/library/items/L5PSZT6L?page=3))

So the different dimensions of political efficacy are not of political efficacy itself, but rather are only distinct dimensions insofar as they relate to dimensions of political participation.

The internal dimension relates to the extent to which one ‘cognitively’ engages with government and politics. That is, the extent to which one takes interest in political affairs, and their degree of understanding and comprehension of government and politics. In this way, the individual “participates” in the most primitive sense of the term: by reading, watching, listening, observing, discussing, and all other means of digesting whatever there is related to politics and government. This is how one can imagine themselves as engaged, and may indeed indicate a higher propensity to participate in the more active sense of the term (though propensity to participate is not participation in fact). Their internal political efficacy thus concerns their perceived capacity to confront the world of government and politics---to feel more or less competent in their ability to ‘cognitively’ engage with this world of government and politics.

“The responsiveness component, on the other hand, began an aggregate decline during the 1960s as citizens became increasingly likely to perceive the government as beyond their sphere of influence.” ([Craig, 1979, p. 228](zotero://select/library/items/93JVZMML)) ([pdf](zotero://open-pdf/library/items/L5PSZT6L?page=4))

And therein lies the clue---why would they perceive this to be the case when rights were being expanded and protections codified? When the external political environment was shifting to become more inclusive, accessible, when civil rights were at the forefront, and when government was responsive to the efforts of public demands? Clearly, this perception conflated with government responsiveness was concerned more with *who* was perceived to be within government favor. From all groups, there was strong reason to view government and institutions as heavily favored towards groups and “people not like me”. Marginalized racial, gender, and sexual minorities marched and fought and died for equal rights and protections from a government easily perceived as against their interests. While concurrently, there was a strong backlash against the VRA and CRA in the 1960s and onward from Whites in particular, likely explaining the sudden loss of the so called ‘responsiveness component’ of political efficacy.  

The effect of changing conditions of the political environment resulted in higher turnout and participation by marginalized minorities. Along with Converse’ notions regarding the increase in educational attainment, more were able to receive higher education. These two things together likely contributed to higher levels of ‘internal political efficacy’---or rather, perceived personal political competence. Yet the stark contrast with external political efficacy clearly tells a different story. The story told over time indicates that more groups of people have come to see the government officials and institutions broadly as not receptive to, nor in favor of, “people like me”.  The wins professed in American history are victories against an oppressive government and political environment, and the losses either nullify prior victories, entrench oppressive conditions, or enact novel forms of oppression. The government writ large is seen as inherently untrustworthy by default, and even more so still when each group compares how well the government favors ‘people like me’ in comparison to ‘others not like me’.

What the author relies on is the notion that external efficacy, or the responsiveness dimension, has the system as the attitude object and not necessarily the actors of that system. Yet what external efficacy survey items appear to measure is this holistic comparison of government favorability for people like me and those unlike me.

“The goal is to establish meaningful conceptual and methodological distinctions among them---meaningful in the sense that the distinctions will be useful in the explanation of individual political behavior.” ([Craig, 1979, p. 228](zotero://select/library/items/93JVZMML)) ([pdf](zotero://open-pdf/library/items/L5PSZT6L?page=4))

And so, it is that the components of political efficacy are dimensional components only insofar as they relate to different characterizations of political participation, or political behavior more generally. The dimensions were conceived instrumentally---that is, for the purpose of something else.

“Input (internal) efficacy\-the degree to which an individual perceives access, or participatory channels, as being open to him. This also implies that one feels competent to avail himself of the opportunity to use these channels should he choose to do so;” ([Craig, 1979, p. 229](zotero://select/library/items/93JVZMML)) ([pdf](zotero://open-pdf/library/items/L5PSZT6L?page=5))

“Output (external) efficacy\-the degree to which an individual perceives his political actions as being (potentially) successful. This introduces the notion of responsiveness, and is the dimension conceptually closest to that of our traditional understanding of the efficacy concept” ([Craig, 1979, p. 229](zotero://select/library/items/93JVZMML)) ([pdf](zotero://open-pdf/library/items/L5PSZT6L?page=5))

“Political trust\-the anticipated quality of government outputs; this is distinguished from output efficacy in that individual influence is not strictly relevant theoretically. Political trust refers to government action perceived as being more in the public interest than as a product of popular demand.” ([Craig, 1979, p. 229](zotero://select/library/items/93JVZMML)) ([pdf](zotero://open-pdf/library/items/L5PSZT6L?page=5))

The following description of each of these different conceptual dimensions is complex, conflicting, and confusing. Moreover, the distinctions are hardly distinctive, nor are the authors expectations. It is as though the proposed conceptual dimensions were written post-hoc, after results showed the degree to which factors were identified and inter-correlated. The re-conceptualization of the three dimensions was actually a postmortem attempt to construct distinct dimensions and their interrelation. The following excerpt is also what leads me to believe this,

“An examination of the final scales illuminates the difficulty in divorcing the elements of effectiveness, opportunity, and outcome in developing indicators. Yet our analysis will support the measurement distinctions made in constructing these scales without denying the very real overlap among them.” ([Craig, 1979, p. 231](zotero://select/library/items/93JVZMML)) ([pdf](zotero://open-pdf/library/items/L5PSZT6L?page=7))

“Output efficacy, as a more refined version of what is normally referred to as &dquo;sense of efficacy,&dquo; seems to be negatively related to extra-system orientation and should be helpful in future studies involving other types of political influence attempts.” ([Craig, 1979, p. 233](zotero://select/library/items/93JVZMML)) ([pdf](zotero://open-pdf/library/items/L5PSZT6L?page=9))

Looking at the items used for "Output efficacy", and in consideration of what is written about the measures for EXTRA, it seems clear that one group holds stronger faith in the conventional methods of the system as taught in schools and in theory (e.g., voting, letters to representatives, campaign involvement, party involvement), whereas the others likely hold less faith in conventional methods (i.e., see them as less effective). Yet neither are in contrast with the notion of efficacy; rather it is the efficacy of chosen method.

Both groups may very well hold strong faith in the notion of popular government or democracy or whatever. This seems to me more of a class distinction of sorts. More about the "appropriateness" of method toward achieving the same end---influencing government officials. It is merely that the authors have constructed the concept and its measure such that higher scores of efficacy is awarded to those who confirm particular beliefs about the system at large which corresponds to particular conventional, unobtrusive methods of political activity. In short, those who believe that the system works and that it resembles or approximates the ideal democratic system---that voting is functional, that there are many ways to "have a say" in what government does, and so on---are awarded with higher scores on the efficacy scale. In essence, the concept "sense of political efficacy", as well as its later component dimensions, are conceived such that higher efficacy corresponds to the "correct" impressions about the political system and processes.

Case-in-point,

“Most obviously, it is hypothesized that input efficacy will be associated with traditional forms of political participation.” ([Craig, 1979, p. 233](zotero://select/library/items/93JVZMML)) ([pdf](zotero://open-pdf/library/items/L5PSZT6L?page=9))





















