---
title: "Davis 2014"
subtitle: "Literature Summary and Notes"
author: "Isaiah Espinoza"
date: last-modified
date-format: iso
bibliography: political-efficacy.bib
format: 
  compact-pdf:
    keep-tex: false
    indent: false
    mainfont: TeX Gyre Pagella
    reference-location: document
reference-section-title: References
---


Davis, Nicholas T. 2014. “Responsiveness and the Rules of the Game: How Disproportionality Structures the Effects of Winning and Losing on External Efficacy.” Electoral Studies 36: 129–36. doi:10.1016/j.electstud.2014.09.003.


> "Thus, political representation gained by electoral winners should significantly alter those individuals' expectations that their preferred policies will be enacted, that “people who voted for a governing party should also be more likely to believe that the government is responsive to
their needs” (Anderson et al., 2005; 28)."

> "Second, because losing is psychologically related to feelings of anger and disillusionment (McCaul et al.,1992; Wilson and Kerr,1999), negative affect that accompanies such losses may manifest itself into a cynical expectation that losers' voices will not be heard. In turn, this may depress external efficacy."

In a 2014 publication by Davis [@davis2014], external political efficacy is measured using items from the Comparative Study of Electoral Systems (CSES) as if these were equivalent to the external political efficacy items utilized in the American National Election Studies (ANES). The two items from the two CSES utilized by @davis2014 as a measure of external political efficacy were,

1.    “Some people say that no matter who people vote for, it won't make any difference to what happens. Others say that who people vote for can make a big difference to what happens”
2.    “Some people say that it doesn't make any difference who is in power. Others say that it makes a big difference who is in power.”


In addition, the definition of external political efficacy in @davis2014 describes the concept somewhat differently from the usual conceptual definition. Although reference is made to the standard definition established by @niemi1991, "...beliefs about the responsiveness of governmental authorities and institutions to citizen demands" [@craig1990, 290; @niemi1991a, 1408],

@davis2014 describes external political efficacy as, "...perceptions about the capacity of and the success to which an electoral system responds to public preferences" [-@davis2014, 130].

Taken apart, Davis describes external political efficacy as conveying, "...the *capacity* of which...an *electoral system*...responds to public preferences" but this doesn't make sense. I think he means to say the capacity of an electoral system to translate vote to seat shares in the legislative body. The extent that disparity exists between vote count and seat apportionment is referred to as disproportionality.   

> "Unfortunately, however, [prior] research does not consider how the institutional rules that structure who “wins” or “loses” an election shape [external efficacy] attitudes. Indeed, because external efficacy is an attitude predicated on perceptions of *institutional* responsiveness, the institutional rules that structure the processes by which individuals gain electoral representation may be indirectly related to external efficacy through this winner-loser mechanism."

Sure but not due the knowledge that people, or voters, have with regard to how the electoral system operates, its procedures, and the like. This would be an external level factor--citizens subject to the electoral conditions determined by the procedure and rules in place--but this doesn't mean that people would be cognizant of it. However, the notion that a particular variable of electoral systems does produce an effect on external efficacy by interaction with voting for a winning party says something different.  


> "If representation is one key component of responsiveness, then we should observe that attitudes of external efficacy are related to both electoral behavior and the very institutional rules that structure electoral outcomes in the first place" [@davis2014, 135]

