---
title: "Democracy for Revisionists"
date: "2025-08-19"
date-modified: last-modified
---

:::{.callout-note}
I originally began writing this on July 25, 2022, and the last time I modified this text was on May 6th, 2024. Over the course of that period I must have incorporated different thoughts on the book because I don't think this is all one coherent review but a collection of entries about this one book. I don't know if it's everything I have or need to say about the book "Democracy for Realists" but what I have here is the start of a substantial critique of the work. 
:::


To them, what democracy is in reality (hence the title) is that which is observed in reality. Citizens are ideologically innocent and dreadfully uninformed about politics, their vote choices are random or mostly predicted by partisan loyalties. Retroactive accountability --in which citizens hold elected politicians accountable for their actions in office by voting them out of office come election time--is not something citizens **actually** do because they hold politicians accountable for things the politicians can't affect. Additionally, citizens are not competent judges of their own conditions, but in the only domain where they are (the economy), they hold politicians to account only considering the few months leading up to an election rather than the length of the politician's term in office. Citizens, generally, are ideologically innocent, meaning they are unwilling or incapable of coherent and constrained ideological reasoning. Conventional folk theory of democracy normatively assumes their general capacity in this regard, which Achen and Bartels deem as mistaken. The people are generally uninterested, uninformed, unwilling or unable to convey coherent policy preferences through issue voting. Finally, citizens, or people in general, are far too irresponsible to consider expanding mechanisms of direct democracy (e.g., initiatives and referendums) because in the cases where citizens were able to vote directly on the issues, shape policy, or mandate it, they voted against their own interests. The consequences of a single case in Illinois is given as the exemplar. Moreover, such mechanisms of direct democracy only empower millionaires and interest groups to use their wealth to achieve their own policy goals.

The whole book is a problem, primarily because it stems from the realist democratic theory, also referred to as revisionist. For one, their opening complaint is that the conventional conceptions of democracy are utopic, and they claim to have falsified the conventional "folk theory" of democracy. However, in the same breath, they offer a "Democracy for realists" defined by what they observe in reality. So they find through empirical observation that elections do not produce the democracy as it is understood in conventional theories, but instead of characterizing the states they observe as not democratic, they revise the very meaning of democracy according to whatever is revealed through empirical observation.


Second, the onus for producing democracy is laid upon the people, but crucially, they presume the full facilitation of democracy by the political system. All the behaviors, attitudes, and requisite virtues these authors and similar others ascribe to the citizen are not based on a particular theory of democracy but based on normative prescriptions of some scholars.

The authors fail to ever consider whether the evidence they present or the conception of democracy they promote may even be characterized as democracy at all. They say the common "folk" understanding is invalid because the evidence shows a much different reality, yet they still refer to this political reality as democracy. It is as though democracy is defined by whatever is revealed by the data (or rather, the interpretation of selectively relevant data). In order to demonstrate that the reality does not meet the silly ideals, the authors turn to the ordinary folk of which the conventional theory pertains.

The implicit assumption is that the people are subject to a system in which they can actualize the conventional ideals of democracy through their engagement and collective action. In other words, the responsibility for current politics and government can only be the people's fault if they are able to determine politics and government. To what extent is that the case?



## Chapter 4: The Logic of Retrospective Accountability

The theory of retrospective accountability suggests that voters only need to monitor their own and the public's well-being and day-to-day experiences in order to evaluate the performance of elected officials in office. The electorate evaluates the *results* of elected officials' performance by evaluating their own and others well-being. The theory accepts the electorate as too uninformed and too disengaged to play a meaningful role in the democratic process - which is the policy making and decision-making process.

Achen and Bartels criticism;

-   Voters have difficulty attributing some result or outcome where it belongs
-   Voters have difficulty in assessing their own and the public's well-being
-   So they may judge that their well-being is shit due to particular and limited economic conditions (e.g., gas prices) despite their general welfare being excellent otherwise, and subsequently fault the President or the opposing party for those economic conditions regardless of the President's ability to effectively influence those economic conditions.


> "To the extent that voters' assessments of their own well-being are erroneous, retrospective voting will succeed much less well in selecting good leaders and in disciplining them to pursue voters' interests." (p.93)

> "valence issues -- that merely involve the linking of the parties with some condition that is positively or negatively valued by the electorate"

> "Observed cross-sectional relationships between retrospective evaluations (for example, assessments of incumbent performance or perceptions of the economy) and vote choices may reflect the electoral impact of retrospective evaluations, but they may also reflect the extent to which retrospective evaluations are constructed to rationalize vote intentions whose real causes lie elsewhere."

> "...in a single snapshot survey *real* national economic conditions are a constant, so *all* of the observed variation in perceived national economic conditions must reflect partisan bias, overgeneralization from personal experience or local conditions, and other vagaries of individual perception." (95-96)

Slight rephrase for myself: a single snapshot of national economic conditions represents reality ("just the facts") which means they are constant, so all the observed variation from people's perception of that national economic reality reflects whatever bias and fallacies plaque them.


:::{.callout-note}
The next section was apparently written on 2024-02-10. I noted previously that part of the following is transcribed from my hand-written notes on 2024-01-22 from my reMarkable 2 tablet
:::

## Real Eyes Realize Real Lies

In "Democracy for Realists", Achen and Bartels begin by describing the "conventional view" of democracy,

> "Ordinary people have preferences about what their government should do. They choose leaders who will do those things, or they enact their preferences directly in referendums. In either case what the majority wants becomes government policy...Democracy makes the people the rulers, and legitimacy derives from their consent." (1)

"Preferences" is how the authors begin describing the ideal "folk theory" of democracy. The conception of democracy premised here conveys the meaning of democracy as *responsive government* (hence the book subtitle). To the authors, the folk theory establishes a conception of democracy that refers to a government *responsive* to the *preferences* of the constituted people. Or rather, the preferences of voters. This means, of course, that the people who vote are the ones who choose (i.e., elect) those who will do things as government. By extension this implies elections as serving to function as some form of accountability.

The crux of the conventional conception of democracy according to the "folk theory", as explained by Achen and Bartels, refers to a political system in which a government is *responsive* to the *preferences* of the *voters*. By this conception of democracy implied under this "folk theory", we may just as well understand the inverse as referring to non-democracies. That is, non-democracies refer to government regimes unresponsive to the people's preferences, and political systems in which government agents are not chosen by, nor held accountable to, the people.

The authors go on to deride the "folk theory" as, "...a set of accessible, appealing ideas assuring people that they live under an ethically defensible form of government that has their interests at heart." (1). One might consider that the authors set up a straw-man conception of democracy only to refute it conclusively in light of the evidence, revealing what democracy "really" is by how democracy really works. However, that criticism would only hold valid suffice a coherent standard consensus on what democracy is--in theory. That is, consensus on a conception of democracy concordant with the meaning of the concept. However, since no explicit standard conception of democracy exists among scholars, it would not be appropriate to criticize the premised "folk theory" as a straw-man.

Nevertheless, the "folk theory" is reductive for a purpose. The "folk theory" the authors start with may be immediately impressed as 'wrong' to any general reader who picks up a book with such a title, but notable is that the "folk theory" appears to be a reductive treatment of democratic theory. Moving from the general conception of ordinary folk, the authors set up two contemporary conceptions of democracy of which they claim to have invalidated, but these are not conceptions necessarily derived from democratic theory. Rather the authors consider two conventional theories based on the groups to which those theories appeal most,

> "We consider two main types of theory, one popular with broad swatches of democratic society and a second whose appeal is largely confined to scholars specializing in the study of elections"

Whereas, the theories and meanings that one may be introduced to and contend with in the study of democratic theory are listed and dismissed in a footnote in the first chapter,

> "These two models by no means exhaust the variety of meanings of democracy around the world, or even within the United States. For example, the (overlapping) traditions of *participatory democracy*, *face- to- face democracy*, and *deliberative democracy* have received a great deal of attention from academic theorists...and they have been implemented with more or less success in a variety of settings, especially in small groups and local communities... However, notwithstanding some creative attempts to employ small-scale deliberative exercises as simulations of how mass publics *would* decide controversial issues in a deliberative fashion...these models seem to us to be less relevant for understanding democratic politics on a national scale than those we consider here." (Achen and Bartels 2016, 2 n2)

Why these aforementioned theories of democracy are not relevant is left unclear until the end of the book, where the authors make clear that ***the assumption of humans as capable by their very nature is untenable according to the evidence they present***. Indeed, the book is a long pessimistic diatribe on the inadequacy of humans to live up to the supposed ideals of the conventional view as well as other highly idealistic models,

> "Instead, much (and much of the best) contemporary political theory has focused on highly idealistic models of *participatory* or *deliberative* democracy (Pateman 1970; Barber 1984; Habermas 1994; Fishkin 1995; Benhabib 1996; Gutmann and Thompson 1996; Macedo 1999; Cohen 2003). These models of democracy emphasize---indeed, they often simply assume--- rationality, mutual consideration, and the patient exchange of publicly justified reasons for supporting specific policies. Thus, they rest on essentially the same unrealistic expectations about human nature embodied in the folk theory. And like the folk theory, they are significantly undermined by what has been learned since the Enlightenment about human cognition and social life (Sanders 1997; Mendelberg and Oleske 2000)." (301)

The argument is thus summarized as a critique and refutation of the assumption that humans are in any way 'rational' enough for 'democracy' to flourish by showing how naturally irrational Americans and people in "...other democratic systems as well" (13) are in general. Quite clearly, the authors pessimistic perception of human nature lies at the heart of the book, despite being informed primarily by studies of American voting behavior and associated theories of voting. Democracy fails because it reflects human nature, and the most salient example of the failure of democracy to these authors is Hitler's rise to power, "The power of this viewpoint is appallingly illustrated by the most spectacular failure of 20th-century democratic politics, Hitler's rise to power via the ballot box." (314). Democracy made Hitler. Such pessimism is nevertheless generalized to humanity as they express wholeheartedly without refrain that the identifiable soul of Nazi Germany is latent within every populace just waiting for more 'democracy' to set it free,

> "In truth, however, the desire for a strong leader who can identify domestic enemies and who promises to do something about them without worrying overmuch about legalities--- those germs, mutated to fit the particular local subcultures, are latent in every democratic electorate, waiting for sufficiently widespread human suffering to provide conditions for their explosive spread." (316)

The authors perversions of democracy as populism isn't new but common among notable realist scholars of the past (Riker 1982; Schumpter 1942). Such concerns of populism are bound to ring true for anyone who assumes that people are generally a bunch of incompetent dumbs, either easily swayed against their better nature or entirely lacking of it[^1].

[^1]: The timing of the books publication couldn't have been more fortunate for this pessimistic view of human nature to flourish within academia, if only evidenced by subsequent reviews of the book in which the election of Donald Trump is referenced to lambaste how, "In 2016, American citizens voted against the wisdom of policy experts and elites" [@schwennicke2017, 148]. Never mind the fact of the popular vote for that election shows otherwise. The irony is the idea that the 2016 election confirms the assertive claims by Achen and Bartels despite the fact that the electoral college decides who will serve as President, and not the popular vote.

Importantly, the notion of "success" marks the undertone of the realist framework the authors have taken. The authors cite to and follow @schumpeter2010 in presenting a "realist" challenge, or what is otherwise known as the "revisionist" critique to classic conceptions of democracy [@osbun1985]. Introducing the touchstone theorist, Frank Cunningham succinctly describes the central thesis of Schumpeter's revisionist/realist challenge,

> "If societies generally called democratic are regarded in terms of how they actually function (hence the realist label) it is obvious, Schumpeter insisted, that they are governed not by the people or by a majority taken as a whole but by elected officials along with nonelected political party and bureaucratic attendants....Schumpeter's conclusion was that the classical conception should be replaced by one in line with the actual functioning of democracy in the modern world. He thus reduced democracy to a method for selecting public officials..." [@cunningham2002, 9-10]

> "Strictly speaking, any political society in which there are free elections is as democratic as any other on this definition, but Schumpeter thought that democracies could still be ranked according to how well they meet the preconditions for the democratic method to 'succeed.' According to him these conditions are: availability of qualified political leaders; assurance that experts and not the public decide matters requiring special knowledge or talents; a well-trained bureaucracy; and a public whose members are tolerant of one another and are prepared to allow politicians a relatively free hand in governing." [@cunningham2002, 10]

The realist agenda of Achen and Bartels, then, is to invalidate the fantastic idea of democracy via demonstrating the incapacity of human beings in general to meet the preconditions for success as just outlined. The prospective success and achievement of ideals of a democratic society are, then, placed squarely upon the shoulders of people--that is, those who are most responsible with producing it, and because of this, "...the folk theory of democracy fails" [@achen2016a, 299].

To these authors, like others of the past aligned with Schumpeter, the idealized conceptions of democracy are as fantastic as they are unhelpful for, "...making government contribute to human welfare" [-@achen2016a, 7]. In this way, they qualify democracy by what "works", that is, by what is 'successful'. Terms like "good government", "effective government", and the like refer to political outcomes that result in some benefit quantifiable. Thus, in yet another way, democracy is that system of government that gets good results; failure is undemocratic and its all the people's fault.

## Whatever is in this box is democracy

@achen2016a do very well to identify the problem of supposition in both popular and scholarly conceptions---that conventional ideals of democracy can serve as qualifying criteria of which to measure how democratic a political system performs despite the ideals being ultimately unattainable. In other words, they recognize that idealized conceptions offer no real path of figuring out, "*What* makes a country democratic and *why* that is a good thing..." [-@achen2016a, 6]. They criticize the lacking conceptual definitions in democratic theory, and disparage those which are especially idyllic. They all but mock the romantic literally and normative gestures to democracy as insufficient for gaining an intellectually stimulating grasp and what makes a democracy and why it would be worthwhile.

Most of the first chapter outlines an irony that echoes throughout the rest of the book. Achen and Bartels, too, criticize the lacking conceptual definitions of democracy as well as the contradictory conceptions of democracy in political theory. The irony lies in the fact that they manage to accomplish even less than the democratic theory (and theorists therein) of which they criticize. Unprepared or ill-equipped to do the intellectual legwork, the authors say, "...we are not prepared to supply...a well-worked-out, new theory of democracy", yet go on to, "...summarize our evidence regarding the failures of existing theories of democracy, clear some of the intellectual ground on which a more realistic theory might be built..." [-@achen2016a, 298]. Even though the authors humor no novel theory of democracy, we are left wanting for what democracy even is since it is definitively not what the "folk theory" says it is.

The argument in "Democracy for Realists" is predicated on there being a 'real' conception of democracy--that is, empirically bounded--despite there not being an uncontested account or definition of the concept at base. At the same time, despite the authors consternation with democratic theory, it appears as though democracy is well associated with "good" and "justice" and even "us"[^2]. So the evidence presented may discount this "folk theory" of democracy as conceived, but considering how democracy is so easily presumed for "...the democratic system we know best, that of the United States" and, "...other democratic systems as well" [-@achen2016a, 13], it seems as though whatever the evidence shows will still be classified as democracy for "realists".

[^2]: Subtext within the writing of this first chapter establishes democracy as the 'ethical' form of government, perhaps indicative of the normative value the authors place on democracy which perhaps also partially explains their presumptions of the U.S. and other states as democratic. Whether liberal or not, democracy appears to be associated with "good", with "justice", and most importantly, with "us". This may not be mere association of the authors, however, as it is common for particular nation-states to be presumed as democratic to further whatever research agenda without getting bogged down in conceptual definitions and classifications of abstract characterizations. Perhaps democracy is presumed for "we good and righteous democrats", suggestive of a potential in which identity protection motivation biases which assumptions are inherent in scholarship and research as it pertains to democracy.

The authors also disparage notions of 'direct democracy' to say that referendums and citizen initiatives are just bad or "ineffective" practices. Little consideration is given as to whether those practices concord with the meaning of the concept, but it is simply implied as dumb because people, in general, are stupid. That is, ordinary people *en mass* are not well qualified according to the prescribed requisites of democratic citizenship to be well informed, interested, engaged, and habitually rational. Like prior authors, the notions of an ideal democratic citizen is laudable but an ideal conception of democracy is laughable. The authors make reference to their work as revelatory of human nature, and go on to suggest that humans, by their nature, are pitiful at best or genocidal at worst.

The authors fail to ever consider whether the evidence they present or the conception they promote may even be characterized as democracy at all. They say the common "folk" understanding is invalid because the evidence shows a much different reality, yet they still refer to this political reality as democracy. It is as though democracy is defined by whatever is revealed by the data (or rather, the interpretation of selectively relevant data). In order to demonstrate that the reality does not meet the silly ideals, the authors turn to the ordinary folk of which the conventional theory pertains.

The implicit assumption is that the people are subject to a system in which they can actualize the conventional ideals of democracy through their engagement and collective action. In other words, the responsibility for current politics and government can only be the people's fault if they are able to determine politics and government. To what extent is that the case?

