---
title: "Esaiasson, Kölln, and Turper 2015"
subtitle: "Literature Summary and Notes"
author: "Isaiah Espinoza"
date: last-modified
date-format: iso
bibliography: political-efficacy.bib
format: 
  compact-pdf:
    keep-tex: false
    indent: false
    mainfont: TeX Gyre Pagella
    reference-location: document
reference-section-title: References
---

Esaiasson, Peter, Ann-Kristin Kölln, and Sedef Turper. 2015. “External Efficacy and Perceived Responsiveness—Similar but Distinct Concepts.” International Journal of Public Opinion Research 27(3): 432–45. doi:10.1093/ijpor/edv003.


> "[External Efficacy] originates from empirical research of public opinion. To explore the idea that citizens value a political system that is sensitive to their demands, Campbell, Gurin and Miller (1954) introduced the concept ‘‘political efficacy’’ and operationalized it through four survey items. Within short time, Lane (1959) added a distinction between internal and external efficacy. Internal efficacy taps an individual’s feeling that he/she has the capacity to participate in democratic processes, whereas EE relates to the perceived willingness of those in power to adhere to citizen opinion." (433)

> "According to [the original Michigan SRC] definition, efficacy is a belief about the consequences of citizen involvement in politics (is it worthwhile to perform one’s civic duties?). As it refers to political processes generally, it asks individuals to evaluate an undefined range of actors commonly involved in authoritative decision making. With its broad reference object, EE captures a general orientation toward the political system (‘‘the political process’’)."  (433)

For what it's worth, these authors are using the old, obsolete definition of political efficacy (before the split into two components) to refer strictly to the conception of external efficacy. The definition of external efficacy after the conceptual split refers to "perceptions of responsiveness to political bodies and actors to citizen demands". Inherent in the definition of external efficacy is government responsiveness. Broadly, yes, but external efficacy still strictly regards government responsiveness. 

Political actors, regime, institutions, political system, etc. are all coalesced into one broad object that encompasses 'government' to which respondents evaluate responsiveness. So yes, the reference object is not precise, but precision doesn't solve the conceptual issue of overlap with government responsiveness narrowly defined or operationalized. 

Ultimately, the concern is with the outcome of interest -- responsiveness of government generally be it the politicians, system, process, etc. Respondents are asked to evaluate whether government, in general, is responsive to their "demands", to public opinion generally, or to their acts of political expression. The key conceptual issue of classic and contemporary measures is failure to clarify what government actors or institutions are supposed to be responsive to beyond general allusions to public opinion as "citizen demand". Some scholarship considers voting an expressive political act; the choices made on the ballot are thought to convey more than simple blatant preferences. 

However, this is problematic. The measure of external efficacy isn't supposed to capture general attitude/orientation to the political system or process, but an evaluation as to their ability to impact politics and government. That is, respondents are evaluating the popular capacity "to impact the political process". This itself a vague but meaningful statement.

The authors here draw on considerable scholarship from the depths of political theory to contemporary research in political science to characterize and conceptualize the proposed concept of perceived [government] responsiveness (see below for relevant excerpt). However when it comes to external political efficacy, the authors utilize outdated conceptual definitions which are now obsolete; contemporary conceptual definitions are not referenced. 

In addition, rather than draw upon theory to scrutinize external efficacy at the conceptual level, the authors unconvincingly argue that the meaning of external political efficacy is distinct from perceived [government] responsiveness. Moreover, the authors assert what measurement captures in reference to the asserted conceptual meaning, "[external efficacy] captures a general orientation toward the political system" [-@esaiasson2015, 433], and also claim that the items used to measure external efficacy are "affectively charged" as though that undermines construct validity somehow.

> "Moreover, the reference to the individual’s ‘‘feelings’’ about the political process means that the efficacy belief is affectively charged." (433)

As opposed to beliefs that aren't "affectively charged"? In a survey item, using the phrase, "how do you *feel* about..." compared to "what are your *thoughts* about..." isn't going to engage different cognitive processes for the respondent. Especially without some specific instruction presented to the respondent. Also, considering that the inquiry is interested in measuring attitudes, there should be absolutely no presumption that any of the reported attitudes aren't "affectively charged". All responses, just as all thoughts, are laden with affect. Moreover, the extet to which this is problematic is unclear and not properly demonstrated. 

> "Terms like ‘‘have a say’’ and ‘‘don’t care much’’ underline that the beliefs are affectively charged." [-@esaiasson2018, 433]

"having a say" doesn't refer to any particular affect, and the evaluation that public officials "don't care much" is laden with affect only because the wording of the survey item is written that way. Thus, any response to that item can be deemed as "affectively charged". Yet even still, it is not clear what that really means to the authors of this study. Respondents only respond to the questions posed as written; the extent to which such items are "affectively charged" must be demonstrated by the researchers and it also must be explained why that is problematic. The issue of external efficacy items making reference to "feelings" *contra* attitudes or cognitive appraisals is a non-sequitur


> "Responsiveness is typically understood as a process in which representatives pay close attention to citizen opinion (Andeweg, 2011). Illustratively, Stimson et al. (1995, p. 543) stipulates that responsiveness is when ‘‘representative governments respond to—meaning acting as a consequence of—charges in public sentiment’’ (see also Manin, Przeworski, & Stokes, 1999, p. 9–10; Powell, 2004, p. 91). Thus understood, responsiveness involves distinct actions from distinct decision makers: To act responsively, representatives must (1) keep track of changes in public sentiments and (2) decide in accordance with these sentiments."
	
> "As PR is natively connected to its root concept, it captures the subjective side of the process: the degree to which representative decision makers are (1) perceived to keep track of changes in public sentiments and (2) are perceived to decide accordingly. The focus on specific acts from specific actors means that attentive citizens may continuously update their responsiveness perceptions in reaction to changes in representatives’ behavior. For example, during the course of a single mandate period, citizens observe (and potentially reflect on) an array of responsiveness actions and processes regarding areas such as welfare politics, tax rates, immigration policies, and
	defense spending."
	
> "Drawing from the above, we can qualify our contention that EE and PR, while overlapping in content, are meaningfully different concepts. EE focuses on highly generalized and affectively charged beliefs about the representative system, whereas PR is centered on beliefs about specific actions of targeted actors."

Overall, the argument professed by the authors is untenable. If anything, the perceived responsiveness they propose is but a narrowed subcategory of the broader concept of perceived government responsiveness in general. External efficacy is conceptually defined as government responsiveness, disregarding the level of specificity when it comes to which actors in government and the ideas about what qualifies them as responsive. 

Moreover, the high intercorrelations between (the latent concepts of) external efficacy and perceived [government] responsiveness render the conceptual distinction dubious. At best, 

Responsiveness as Interaction

> "This far we have focused on responsiveness actions that signal a bottom-up relationship in which influence runs from citizens to representatives (as citizens change, so do representatives). However, this is an oversimplification of the representative relationship. Representation theories generally agree that representation requires autonomy on the part of representatives, and that representatives cannot be bounded by instructions from the represented (for reviews, see Dovi, 2011; Urbinati & Warren, 2008). Therefore, a more comprehensive understanding of responsiveness accounts for a two-way relationship in which representation also travels top-down. Specifically, a full account of democratic representation acknowledges that representatives continuously offer policy views, make representative claims, and shape citizen preferences (Disch, 2011; Manin, 1997; Mansbridge, 2003; Urbinati, 2006). From this follows that responsiveness can be seen as a two-way communicative process."

> "The view of responsiveness as a communicative process was presented already in Hanna Pitkin’s (1967) classic The Concept of Representation. Having famously argued that representatives should act in the interests of the represented (rather than slavishly mirroring citizens’ current preferences), she explains how the connection between representatives and the represented can be maintained in the wake of disagreement:

> ‘‘[Representatives] must not be found persistently at odds with the wishes of the represented, without good reason in terms of their interest, without a good explanation of why their views are not in accord with their interests’’ (Pitkin, 1967, p. 209–10, emphasis added).
	
> "When translated to real-world conditions, this means that elected representatives may follow their own best judgment when deciding common matters, but when citizens disagree about the right course of action, representatives are obliged to provide convincing justifications for their deviation. Responsiveness, therefore, should be understood as a promise of sincere communication, ‘‘not of adaptation in the short-term’’ (Esaiasson, Gilljam, & Persson, 2013, p. 24). Taking this theoretical consideration into account, responsiveness incorporates a third type of action from representatives: to provide credible justifications for decisions that counter citizen preferences (Esaiasson et al., 2013, p. 24–5). 

> "In summary, we maintain that PR covers beliefs about how well representative decision makers perform three acts: to listen (keep track of citizen sentiments), to explain (give credible accounts for their actions), and, when called for, to adapt (adjust decisions in the direction of citizen sentiments)."
	
	
Measures

	> "We will use two alternative measures of PR. The first consists of three items, with one indicator per type of responsiveness action (henceforth PR3). Respondents rated the extent to which decision makers have 
		> (1) ‘‘found out about the wishes of citizens,’’ [LISTEN]
		> (2) ‘‘explained their policies to citizens,’’ and [EXPLAIN]
		> (3) ‘‘tried to accommodate the wishes of citizens.’’ [ADAPT]
	> In a first trial pertaining to the PR of the Swedish government in the period 2006–2010, PR3 provided encouraging results when administered to a representative sample of voters (Esaiasson et al., 2013, p. 26–8).1 " (435)


		1 The American National Election Study (ANES) offers a two-item ‘‘government responsiveness index.’’ The items, which originate from the 1964 study, are worded as follows: ‘‘Over the years, how much attention do you feel the government pays to what the people think when it decides what to do?’’ and ‘‘How much do you feel that having elections makes the government pay attention to what the people think?’’ These items are used less frequently in empirical research. They refer to different expressions of public sentiments (‘‘what the people think’’ vs. ‘‘having elections’’), and they empirically overlap with external efficacy items. For instance, Niemi et al. (1991, p. 1407–10) chose, without further discussion, to group the two items with their measures of external efficacy (see also Morrell, 2003, p. 596).

	> "The alternative measure was developed for this study to test for sensitivity to wording; it consists of five items (henceforth PR5). Compared with PR3, it describes the act of listening in more active terms, it draws a distinction between justifications before and after decisions, and it asks directly about whether representatives ‘‘care about citizen views.’’ Table 1 summarizes the two instruments along the measure of EE that will serve as a point of contrast." (435)


## Two alternative measures of Perceived Responsiveness ##

PR3

Representatives between elections….

	- "Find out about citizen wishes?"
	- "Explain their politics to citizens?"
	- "Try to accommodate citizen wishes?"

PR5

Representatives between elections…

	- "Keep themselves informed about citizen views?"
	- "Care about citizen views?"
	- "Provide reasons for actions they have taken?"
	- "Provide reasons for actions they are going to take?"
	- "Decide in line with citizen views?"


A standard measure of External Efficacy

	1. Representatives [NL: Parliamentarians] do not care about the opinions of people like me.
	2. People like me have no influence at all on government policy
	3. Political parties are only interested in my vote and not in my opinion* 

	*This third item was part of the efficacy battery in the U.S. national election studies between 1968 and 1980.


# Results of Measurement Models

Summarized: 
Two main findings

	- Perceived responsiveness and external efficacy are closely interrelated.
	- Results support the idea that PR and EE are distinct constructs

# Results: Predictive validity

Authors predicted that EE and PR independently contribute to political trust attitudes. If PR contributes to trust attitudes even when taking EE into account (i.e., controlling for EE), it provides evidence that PR captures distinct political considerations.

	> "Political trust is measured with three indicators pertaining to trust in parliament, trust in politicians, and trust in government…"
	> Education and Political interest were included as controls.

Summarized: 
Both PR and EE contribute independently to political trust. Authors reproduced findings that external efficacy is associated with high levels of political trust, but also, perceived responsiveness has additional predictive power.
Additionally, PR3 and PR5 measurement models perform equally well in predicting trust attitudes.



### FROM THE SUPPLEMENTARY DATA


Introductory question wordings PR:
 
Test 1
PR: Generally speaking, would you say that elected politicians … 

 
Test 2
We will now ask a few questions about your view about the representative system after elections.
 
PRincumbent: If you think about the current government after the 2010 election, to what extent would you say that it … 
 
PRregime: If you think about elected politicians in general, to what extent would you say that they … 
















