---
title: "lebo2015"
---

## Citation
Lebo, Matthew J., and Christopher Weber. 2015. “An Effective Approach to the Repeated Cross‐Sectional Design.” American Journal of Political Science 59(1): 242–58. doi:10.1111/ajps.12095.

## Notes and excerpts

> "Alternately, one can skip individual-level analyses by collapsing data into mean values and applying time-series analyses to the aggregate data." [@lebo2015, 243]

Aggregating data by year reduces the number of observations $N$ quite dramatically. The dynamic time-series examination of the repeated (rolling) cross-section data aggregated by yearly average values is proposed as an attempt to better understand what is being measured at the individual level. 

> "Studying data in the aggregate has theoretical support if causal ordering at the individual level is in question" [@lebo2015, 243-244]

> "If some independent variables vary only over time (e.g., the inflation rate) there is a natural tendency to construct a model in the aggregate. Yet, aggregating participants by day/week/month/quarter can reduce data sets to a thousandth of their original size." [@lebo2015, 244]

> "Since a multilevel model allows the use of all the data, the aggregate- versus individual-level debate is a false dichotomy. Researchers can explore complex relationships rather than entirely avoid an important level of analysis. In doing so, they can also investigate individual-level relationships that might vary over time." [@lebo2015, 244]

> "Thus, two problems are evident. First, most published work using RCS has relied on techniques that study static or dynamic processes, not both. Second, ventures into MLM with RCS data have barely considered the statistical consequences of the various modeling choices. Given the wealth of RCS data available, we explore its challenges and consider the efficacy of several modeling choices." [@lebo2015, 244]

> "In a true panel design, N units are observed repeatedly over time, yielding an N × T data set and making autocorrelation likely in two directions. First, unit i at time t will be more correlated with unit j at time t than with unit j at other times. Second, the values for each unit i are likely correlated with each other over time."

> "For example, in a Country by Year data set, regression errors are likely to be correlated within years as well as for each country. **Importantly, neither type of autocorrelation disappears in an RCS design even though units are not repeated**."

> "First, dynamic autocorrelation remains. Memory over time, traceable through aggregates, likely exists between units more proximate to one another. If $\bar{Y_{t}$ and $\bar{Y_{t+1}$ are correlated, then εi,t is correlated with εj,t+1 more than εi,t is correlated with $\varepsilon_{k,t+2}$. This holds since observations within each time-point are dispersed around a mean correlated with the mean of the adjacent time-point."

> "How are these challenges to be handled? To begin, two common PCSTS approaches cannot or should not be used. Including a lagged dependent variable (LDV) is a popular way to handle problems of nonstationarity in PCSTS and traditional time series (Keele and Kelly 2006)."

> "A second alternative, looking at the differences in observations between time-points to render a random-walk series stationary, is also popular (Enders 2004)."

> "Yet, since each observation occurs but once in RCS data, these approaches cannot work. Values of $y_{i,t–1}$ are not available, so an LDV is not possible, nor is the use of a differenced dependent variable, $y_{i,t}$, created as $y_{i,t} – y_{i,t–1}$."

> "A third unworkable approach, the use of panel-corrected standard errors (Beck and Katz 1995), is premised on observations repeating in every time-point (a true panel) and does not solve the potential bias in coefficients."

