---
title: "Concept and Measurement of Political Efficacy"
subtitle: "A review of the literature"
author:
  # Add additional authors here if needed, by replicating the above entries.
  - name: Isaiah Espinoza
    affiliation: University of Maryland, College Park
    email: gespinoz@umd.edu
abstract: |
  
format:
  turbo-pdf:
    keep-tex: true
    indent: true
    mainfont: Garamond
    fontsize: 12pt
    colorlinks: true
    linestretch: 1.5
    reference-location: document
reference-section-title: References
bibliography: prospectus.bib
---

# Sense of Political Efficacy 

In an appendix in "*The Voter Decides*", @campbell1954 introduced the concept and initial measure of political efficacy which they believed was related to political activity. These authors referred to this variable as "sense of political efficacy" which they defined as "...the feeling that individual political action does have, or can have, an impact upon the political process, i.e., that it is worth while to perform one's civic duties." (187).

Between the 1950s to 1970s, researchers concluded after some theoretical consideration and empirical examination that political efficacy was comprised of two components, internal and external political efficacy [@lane1959a; @converse1972]. The original concept lacked a strong theoretical foundation, which led to subsequent research intent on reinterpreting the meaning of the survey items. It is with @lane1959a that the two dimensions of political efficacy begin an asymmetric development, writing in "*Political Life: Why People Get Involved in Politics*". He bases much of his consideration of individual political efficacy upon a quality he refers to as "ego strength",

> "Lying behind the capacity to assert oneself against the environment is the general concept of *ego strength*, a quality which is usually associated with the capacity to order one's life in a rational fashion, controlling at once the impulses which rise anarchically to the surface from within, and external events, in so far as they can be controlled....A person with a weak ego, one that has been thwarted in its development by repressive measures or simply never encourage to develop--"babified," so to speak--will tend to view the social scene as something over which he has no control." [@lane1959a, 147, emphasis original]  

@lane1959a assessed that political efficacy distinguishes into two component internal and external sub-dimensions relating to "...the image of the self and the image of democratic government" (149).

> "Men who have feelings of mastery and are endowed with ego strength tend to generalize these sentiments and to feel that their votes are important, politicians respect them, and elections are, therefore, meaningful processes. This constellation of attitudes has been variously called "a sense of political efficacy," "political self-confidence," and, in reverse, "sense of political futility. It has, of course, two components--the image of the self and the image of democratic government--and contains the tacit implication that an image of the self as effective is intimately related to the image of democratic government as responsive to the people." [@lane1959a, 149].

Since then, more recent research has formulated an adjusted definition and measurement of political efficacy by breaking it up into two distinct components: internal and external political efficacy. The former refers to one's confidence in their competence "to understand and to participate effectively in politics" [@craig1990, 290]. The latter refers to perceptions of responsiveness of government to citizens' demands [@niemi1991a]. 

Political efficacy went from originally being considered a unidimensional concept to a multidimensional one. Solidifying the divide of political efficacy into its internal and external components was @balch1974's analysis, which applied a unique multitrait-multimethod matrix method [@campbell1959] to test the construct validity of survey measurement items. Later analysis further bolstered the internal and external dimensions [@hayes1993; @morrell2003].

Dividing the concept into two components, internal and external, didn't necessarily resolve issues as they concern construct validity. Research in the late 1980's and early 1990's focused on establishing a valid and reliable measurement for internal and external political efficacy [@niemi1991a; @craig1982; @craig1990]. In so doing, researchers formulated a reliable measurement scale for internal political efficacy but it remained somewhat unclear what external political efficacy measures really captured [@niemi1991a][^1]. Crudely put, when researchers seek to assess levels of political efficacy among the public, they ask, "how good do you think you are at understanding and doing politics?" and, "are you satisfied with responsiveness of government to people like you?" 

Available measures of internal political efficacy are largely comprised by survey items that ask respondents to self-appraise their own competency to comprehend and confront politics[^2]. Simply stated, internal efficacy is conceptualized and measured as a certain kind of political self-confidence. Internal political efficacy is useful as it relates to explaining turnout, participation, and other behaviors of interest in political science. However it is perhaps better understood if referred to as *political confidence* or *personal political competence* [@converse1972]. Nevertheless, previous research has found that higher internal efficacy makes people more likely to feel like they understand politics [@morrell2003].

External political efficacy, being the lesser developed component, has been far more troublesome. External efficacy is often understood as government (or policy) responsiveness and is measured by two items which construct the external efficacy index on the American National Election Studies (ANES)[^3]. Compared to internal political efficacy, external political efficacy isn't conceptually clear but has been shown to be distinct from its most closely associated concept: government responsiveness [@esaiasson2015]. Despite this, most research conceives of external efficacy as relatively interchangeable with government responsiveness. In addition, findings from time-series analysis show that people are relatively unresponsive to changes in the political environment, reporting that, "aggregate external political efficacy does not appear to be dynamically responsive to changes in the political environment" [@chamberlain2012]. This results in weaker construct validity and, by extension, significant ambiguity over what available measures really capture.

The murkiness of the various related concepts to political efficacy make it difficult to understand what external efficacy refers to exactly since it is demonstratively distinct from government responsiveness [@esaiasson2015]. Moreover internal political efficacy is not distinguished from subjective political competence in the literature [@lane1959a; @converse1972; @craig1982; @craig1990; @craig1979; @niemi1991a; @morrell2005]. Which means, in other words, that researchers conflate an individual's judgement of *efficacy* to produce or achieve intended outcomes, with *confidence* of their own political awareness, interest, and competence. Of course, these two are related, but a person's self-confidence may vary considerably due to influences that have little to do with politics. Additionally, we would expect that a person's sense of political efficacy would be responsive to changing political conditions of society, but that doesn't appear to be the case [@chamberlain2012].

# Adding Dimensions to Political Efficacy

Researchers elsewhere have questioned the two dimensional approach to studying political efficacy, most often adding more dimensions to the concept [@gildezuniga2017; @lee2006]. @gildezuniga2017 proposed a new dimension referred to as '*Government Political Efficacy*', which was described as focusing, "...specifically on perceptions of how the government articulates claims and demands that emerge from citizens to provide them with what they need and deserve." (577). Measurement of this novel dimension of efficacy was based on attitudes supposedly related to the competency of one's government[^4]. Showing results from confirmatory factor analysis using standardized structural equation modeling coefficients, the authors claim that Government political efficacy is revealed to be distinct from both internal and external efficacy. Perhaps as a methodological issue, @gildezuniga2017 use a total of seven items for their Government efficacy measure, but limit the items measuring internal and external efficacy down to two each. Considering they rely on confirmatory factor analysis, more items for one measure may be more likely to produce such results in comparison to traditional internal and external efficacy measures. Additionally, it appears rather dubious that the question wording content of the measurement items are fully distinct from the other two internal and external components.

Drawing more directly on perspectives from social psychology and rationalist models of collective action, [@lee2006] proposes another dimension of political efficacy aptly named '*Collective Efficacy*', which he defines as, "...a citizen’s belief in the capabilities of the public as a collective actor to achieve social and political outcomes" (297). Lee examines data from survey samples in Hong Kong around 2005-2006 to test the hypothesis that collective efficacy is a separate and significant dimension of political efficacy (among others). Like others [@coleman1976; @wolak2018], Lee argued that the impact of political efficacy on political activity is dependent on the context of the political system and environment. Writing in 2006, his studies focus on Hong Kong, "...a society undergoing a process of constrained and gradual democratization. It is a transitional society where the political system is expected to undergo further changes." [@lee2006, 298]. As such, the relationship between political efficacy and participation was of chief interest, and more so as it concerned protest participation [@lee2010] rather than simply voter turnout. The measure employed by Lee is relatively modest, as it includes two survey items to measure collective efficacy[^5] alongside two items measuring internal efficacy and two for external efficacy[^6], with only slight difference in wording for the classic measures. 

Lee finds weak correlation among the three measures, bolstering support for the novel third dimension of political efficacy. However, Lee's measure of collective efficacy may be anchored to the identity of the group and the individual respondent's identification with that group, which may undermine the extent to which such a measure informs us on the "…citizen’s belief in the capabilities of the public as a collective actor to achieve social and political outcomes." Indeed, what the measure may capture is the individual's belief in the capabilities of "my people" or whatever group of people are specified. The measure of collective efficacy relies on the identity of the group, "the collective action of Hong Kong people…" but does not control for identification strength with Hong Kong people despite identifying the group specifically, nor does the study control  for attitudes of patriotism or nationalism. These factors are likely to impact the perceived efficacy of "my people's" collective efficacy to some degree. This is somewhat confirmed in subsequent research by @wolak2018. 

In addition to the construct ambiguity, the items measuring external efficacy invoke seemingly innocuous "people like me" wording which may inadvertently make identity a salient factor (e.g., partisan, racial and ethnic, socioeconomic class). Inclusion of "people like me" may be problematic as it may implicitly conjure up group-level considerations. A study by @wolak2018 appears to suggest this, although her inquiry did not focus upon these potential question wording effects. Rather, Wolak examines how variation of the political context at the state level (contra. national level) may influence feelings of political efficacy. She argued, "…that feelings of efficacy are responsive to people’s opportunities for political influence, shaped by the actions of government and informed by the character of the political context." [@wolak2018, 764], and hypothesized that political efficacy should increase when citizens have greater opportunities "for voice" and when government "delivers desired policy outcomes". Thus, she investigates how policy congruence, descriptive representation, election administration, and ballot initiatives influence political efficacy. Importantly, however, she includes measures of partisanship and ideology to account for whether people feel more (externally) effective when "My government" represents the partisanship of "people like me". 

Wolak does take note of current concerns with the question wording of survey items which are said to measure external political efficacy, "The generalized wording of the ANES efficacy items could help explain why scholars have found inconsistent evidence for state factors shaping citizen efficacy" [@wolak2018, 770]. However, despite the contention, she changes little about the usual measurement of external political efficacy beyond having response items make specific reference to "My state government" and adding another item[^7].

Wolak's findings replicate the distinction between internal and external efficacy, even when focused on state-level politics. She also finds that external efficacy is low at the state level just as it is at the national level, showing an average score of 0.39 on her external efficacy scale where 1 reflects strong agreement with all three external efficacy items. When compared to the national government, however, people on average reported stronger agreement with the idea that state government cares about "what people like me think". That is, State government is considered more responsive than national government.

However, Wolak finds that, "…feelings of political influence follow from partisan congruence. When people share the same partisan leanings as party that controls the state legislature, they are more likely to feel that state politicians listen to them." [@wolak2018, 773]. This finding adds to the concern that the question wording of the survey items referring to "My state government" and "people like me" likely tap into associated identities, deviating as a measure of efficacy to a measure of satisfaction or content. She also finds the same in terms of ideology and a state's policy outputs, "...ideological congruence promotes feelings of external efficacy in state politics. People report greater external efficacy when their ideology aligns with that of the state’s policy outputs." [@wolak2018, 775].

# Conclusion

These findings suggest that responses deviate from being a valid measure of the construct, undermining the extent to which we may ascertain a person's judgement about their own or the popular capacity to produce desired political outcomes. It also highlights concerns regarding the conceptual and empirical overlap between external efficacy and perception of government responsiveness. When conjoined with responsiveness, political efficacy may be high to the extent that a citizen is satisfied with government and politics, be it the actions taken, the political figures themselves, or the successful passage or enactment of some particular policy. Considering the effects that partisanship has on how citizens evaluate their satisfaction with other domains of political relevance (e.g., the economy), trust in government, or approval ratings, it seems care has not often been taken to differentiate the efficacy to produce political outcomes from momentary or partial satisfaction with government figures. When researchers want to know whether and to what extent people believe that political activity can produce political outcomes and achieve political goals, they may otherwise end up capturing the impressionistic sense of satisfaction individuals have with government at the time. 

Conceptual clarity is important, for academics and everyone else. Especially when it comes to measuring those constructs believed, or demonstrated, to be significant to political attitudes and behavior. For the most part, the significance of studying political efficacy has concerned its relationship and impact upon individual political activity. In particular, its importance has been relegated in helping to explain variation in electoral participation. However, the way in which political efficacy has been conceived has led to contemporary measures capturing self-appraisals of political competence dependent on personal confidence and impressions of government responsiveness without delineation of a clear metric or distinction from similar concepts. If a researcher wants to know whether and to what extent people believe that they have the capacity to produce desired or intended political outcomes and hold government accountable through individual or collective political activity, the concept and measures of political efficacy currently available aren't clearly useful to that end.

\newpage

[^1]: In note 4 of the work cited, the authors note that the two items meant to capture external efficacy "are tapping something quite different from the new efficacy questions....whatever they do measure...they *do not* measure internal efficacy" (italics in original).

[^2]: Survey participants respond to measurement items for internal political efficacy on a five-point Likert response scale from *strongly disagree*, *somewhat disagree*, *neither agree nor disagree*, *agree somewhat*, and *strongly agree*. There are four internal efficacy items: "I consider myself to be well qualified -to participate in politics." (SELFQUAL);  "I feel that I have a pretty good understanding of the important political issues facing our country." (UNDERSTAND); "I feel that I could do as good a job in public office as most other people." (PUBOFF); ‘‘I think that I am as well-informed about politics and government as most people.’’ (INFORMED)

[^3]: Following the same five-point Likert response options, there are two basic external efficacy items: "People like me don't have any say about what the government does." [NOSAY]; "I don't think public officials care much what people like me think." [NOCARE].

[^4]: Measuring Government Efficacy on a 10-point Likert scale, presumably ranging from strong agreement to strong disagreement. The authors list seven survey items: “my government works on everyone’s behalf,”; “my government makes decisions based on what citizens want,”; “our political institutions (e.g., Congress, political parties, etc.) represent all citizens,”; “my government provides citizens with efficient services,”;	“today’s American democracy works well,”;	“American democracy is the result of everyone’s input,”; and “my government’s decisions are transparent”

[^5]: Using a five point Likert scale from strongly disagree to strongly agree, the measurement items for collective efficacy consisted of two items: "the collective action of Hong Kong people has a huge influence on public affairs"; and "the collective action of Hong Kong people can improve society". 

[^6]: Though Lee conforms to the traditional measures of internal and external efficacy generally, the wording of the survey items changes slightly. Items used to measure internal efficacy: "I have enough ability to understand political matters"; and "I have the ability to talk about and participate in public affairs". The items used to measure external efficacy: "the current political system in Hong Kong responds to public opinion effectively"; "the Hong Kong Special Administrative Region government responds to public opinion effectively". Notable is that one of the external efficacy items makes reference to the responsiveness of the political system rather than government actors, whereas the other references a specific government body. 

[^7]: The measures for external efficacy in @wolak2018's study follow the five point Likert scale and consist of three measurement items: "My state government is responsive to what the people in my state want."; "Most elected officials in my state government care what people like me think."; "I feel my voice is heard in state government decisions that affect me." It is interesting to note the similarities and differences between these items and the classic NOSAY and NOCARE measures for external efficacy.





