---
title: "Merolla, Sellers, and Fowler 2013"
subtitle: "Literature Summary and Notes"
author: "Isaiah Espinoza"
date: last-modified
date-format: iso
bibliography: political-efficacy.bib
format: 
  compact-pdf:
    keep-tex: false
    indent: false
    mainfont: TeX Gyre Pagella
    reference-location: document
reference-section-title: References
---


> "Political efficacy is an important psychological orientation that has been used extensively by scholars to help explain voting and other forms of participation. However, very few scholars have sought to treat political efficacy as a dependent variable. In this research note, we look at the linkage between descriptive representation and political efficacy. Drawing from existing literature, we argue that an increase in descriptive representation positively affects levels of political efficacy. We examine support for this argument by looking at whether levels of efficacy increased among African Americans after the election of Barack Obama using data from the 2008–2009 American National Election Studies (ANES) panel study. We find that the effects of descriptive representation on efficacy varied depending on one's partisanship. Black Republicans, Independents, and weak Democrats experienced an increase in efficacy. However, Black Democrats and White Democrats who strongly identify with the party experienced a similar boost in efficacy, which suggests that partisanship can override the effects of having a descriptive representative."


Relevant portion of absract repeated below

> "We find that the effects of descriptive representation on efficacy varied depending on one’s partisanship. Black Republicans, Independents, and weak Democrats experienced an increase in efficacy. However, Black Democrats and White Democrats who strongly identify with the party experienced a similar boost in efficacy, which suggests that partisanship can override the
effects of having a descriptive representative."

> "We use data from the 2008–2009 ANES panel study. The panel study consisted of tracking and
repeat interviews with the same group of respondents from January 2008 through May 2009.We focus
on the difference between the February and November waves to compare feelings of efficacy before
Barack Obama had secured the nomination to after the election; the September and November wave,
to explore how efficacy shifted from early in the general election campaign to after the election; and, September to May of 2009, once Barack Obama had been in office for several months."

wave 1: Feb and Nov 2008
wave 2: Sep and Nov 2008 (this is early in the general election?)
wave 3: Sep and May 2009


> "Three efficacy questions were present on all four waves: (1) “How much can people affect
government?”; (2) “How much do government officials care?”; and (3) “How often does government
do what most people want?” Response options were on 4-point scales ranging from “not at all” to “a great deal” for questions 1 and 2 and “never” to “always” for question 3. All three variables are coded such that higher values indicate more positive feelings of efficacy. Since the three variables capture similar concepts, a summary measure of efficacy was created by adding the three efficacy measures for each wave." [867]


From footnote 7 on this page,

> "The Cronbach’s alpha for each wave is as follows: February (0.73), September (0.69), November (0.77), and May (0.77). Since some of the measures tap into internal efficacy and others external efficacy, we further confirmed that using an additive scale is valid by running principal-components factor analysis. Only one factor emerged in each wave, and the rotated factor loadings were very similar across the three measures." [867, n7]


The authors don't provide the exact wording of the question items, but the wording differs slightly. I'll also have to see if the panel data these authors refer to are available because from the 2008 pre- and post-election ANES data I have for 2008, I can't find the third question they list.

They also don't note that the ANES was testing two different versions of political efficacy questions for both internal and external efficacy. They are referencing version D in their study, but version C were the standard political efficacy items. 

[vers.D] E10c. How much do public officials care what people like you think?
[vers.D] E10d. How much can people like you affect what the government does?
[1 = great deal…5=not at all,  -1=inap, -8=dk, -9=refused]
