---
date: "2023-03-28, 12:15:58"
---

::: {.callout-note}
Created: {{< meta date >}}
Modified: {{< meta date-modified >}}
:::

# What is this?

A consolidated list of the various definitions of political efficacy, internal political efficacy, and external political efficacy that I have come across throughout my studies. 


# Definitions of Political Efficacy

-   Campbell, Angus, Gurin Gerald, and Warren E. Miller. 1954. The Voter Decides. Evanston, Ill.: Row, Peterson.

> "Sense of political efficacy may be defined as the feeling that individual political action does have, or can have, an impact upon the political process, i.e., that it is worth while to perform one's civic duties. It is the feeling that political and social change is possible, and that the individual citizen can play a part in bringing about this change." [@campbell1954, 187]

Five items (calling for a simple "agree" or "disagree" response) were included in the pre-election questionnaire. These items were:

1.  "I don't think public officials care much what people like me think." [Disagree = 1]
2.  "The way people vote is the main thing that decides how things are run in this country." [Agree = 1]
3.  "Voting is the only way that people like me can have any say about how the government runs things." [Disagree = 1]
4.  "People like me don't have any say about what the government does." [Disagree = 1]
5.  "Sometimes politics and government seem so complicated that a person like me can't really understand what's going on." [Disagree = 1]

Efficacious = 1, futile = 0. Campbell et al. (1954) explained how they coded the items,

-   ""Disagree " responses to items 1, 3, 4, and 5, and an "agree " response to item 2 were coded as "efficacious." To respond in contrary fashion (i.e., to think that public officials are not responsive to the will of the electorate, to feel that most major policy decisions are the work of "wire-pullers" and pressure groups and the product of "backroom deals," to be unaware that means of expressing one's political wishes other than voting are available to the average citizen, and to be of the opinion that the modern complexities of government have made citizen participation either impossible or unavailing) indicates a high degree of political futility."



#------------



Craig, Stephen C., Richard G. Niemi, and Glenn E. Silver. 1990. "Political Efficacy and Trust: A Report on the NES Pilot Study Items." *Political Behavior* 12(3): 289--314.



Niemi, Richard G., Stephen C. Craig, and Franco Mattei. 1991. "Measuring Internal Political Efficacy in the 1988 National Election Study." *American Political Science Review* 85(4): 1407--13. doi:[10.2307/1963953](https://doi.org/10.2307/1963953).


_Internal efficacy_ -- "referring to beliefs about one's own competence to understand and to participate effectively in politics" [@craig1990, 290; @niemi1991a, 1407].

_Internal efficacy_ "indicates individuals self perceptions that they are capable of understanding politics and competent enough to participate in political acts such as voting." [@craig1982, 86]

(Note that @craig1990 initially stressed the importance of including at least six of the seven items for measuring internal political efficacy. Subsequent follow on research by @niemi1991a concluded that the top four items below constitute a valid and reliable measure of internal efficacy. Nevertheless, I include the other items for posterity.)

1.  "I consider myself well-qualified to participate in politics" [SELFQUAL]
2.  "I feel I have a pretty good understanding of the important political issues facing our country" [UNDRSTND]
3.  "I feel that I could do as good a job in public office as most other people" [PUBOFF]
4.  "I think that I am better informed about politics and government as most people" [INFORMED; 1988 and after]
  4a. "I think that I am as well-informed about politics and government as most people" [INFORMED; Prior to 1988]

5.  "Other people seem to have an easier time understanding complicated issues than I do" [OTHERS]
6.  "I often don't feel sure of myself when talking with other people about politics and government" [NOTSURE]
7.  "Sometimes politics and government seem so complicated that a person like me can't really understand what's going on." [COMPLEX]**


**Note that this item was initially included in the internal efficacy set, but showed weakest correlation with the other items and also loaded on external efficacy. It is usually not included in measurement of internal efficacy. 


_External efficacy_ -- "...beliefs about the responsiveness of governmental authorities and institutions to citizen demands" [@craig1990, 290; @niemi1991a, 1408].

_External efficacy_ "measures expressed beliefs about political institutions rather than perceptions about  one's own abilities .... The lack of external efficacy . . . indicates the belief that the public cannot influence political outcomes because government leaders and institutions are unresponsive to their needs" [@craig1982, 86]

1.  "Public officials don't care much what people like me think" [NOCARE; 1994 onward]
  1a.  "I don't think public officials care much about what people like me think" [NOCARE; prior 1994]
2.  "People like me don't have any say about what the government does." [NOSAY]

**Regime-based efficacy**---"the expectation that conventional rules and procedures for policy formation and implementation facilitate (rather than impede) citizen inputs" 


> "Shingles (1988, p. 7) described **regime-based efficacy** (RBE) as "the expectation that conventional rules and procedures for policy formation and implementation facilitate (rather than impede) citizen inputs"; as operationalized for this study, the emphasis was on whether or not respondents perceived "open and fair access to incumbents" ibr citizens who wished to influence the political process or its outcomes."




Balch, George I. 1974. "Multiple Indicators in Survey Research: The Concept 'Sense of Political Efficacy.'" *Political Methodology* 1(2): 1--43.



Converse, Philip E. 1972. "Change in the American Electorate." In *The Human Meaning of Social Change*, eds. Angus Campbell and Converse Phillip E. Russell Sage Foundation, 263--338.

-----------------------------

Craig, Stephen C., and Michael A. Maggiotto. 1982. "Measuring Political Efficacy." *Political Methodology* 8(3): 85--109.



-   _Internal efficacy_ "indicates individuals' self-perceptions that they are capable of understanding politics and competent enough to participate in political acts such as voting."
-   _External efficacy_ "measures expressed beliefs about political institutions rather than perceptions about one's own abilities...The lack of external efficacy...indicates the belief that the public cannot influence political outcomes because government leaders and institutions are unresponsive to their needs."

Quoting from American National Election Studies Data Sourcebook, 1952--1986


#--------------

Craig, Stephen C. 1979. “Efficacy, Trust, and Political Behavior: An Attempt to Resolve a Lingering Conceptual Dilemma.” American Politics Quarterly 7(2): 225–39. doi:10.1177/1532673X7900700207.


"*Output (external) efficacy*---the degree to which an individual perceives his political actions as being (potentially) successful. This introduces the notion of responsiveness, and is the dimension conceptually closest to that of our traditional understanding  of the efficacy concept" [@craig1979, 229]

“*Input (internal) efficacy*---the degree to which an individual perceives access, or participatory channels, as being open to him. This also implies that one feels competent to avail himself of the opportunity to use these channels should he choose to do so” [@craig1979, 229]

"*Political trust*---the anticipated quality of government outputs; this is distinguished from output efficacy in that individual influence is not strictly relevant theoretically. Political trust refers to government action perceived as being more in the public interest than as a product of popular demand." [@craig1979, 229]

:::{.callout-note}
NOTE: the following is from end-note 3 on page 237
:::

The following items comprise the final versions of the scales for input and output efficacy and political trust. The response in parentheses indicated high efficacy or trust: 
A. *Input Efficacy*: 
  (1) A person like me could never get elected to public office. (Disagree) 
  (2) Sometimes politics and government seem too complicated that a person like me can’t really understand what’s going on. (Disagree) 
  (3) Most public officials wouldn’t listen to me no matter what I did. (Disagree) 
  (4) In today’s world, votes don’t speak loud enough; nowadays, you have to shout to be heard. (Disagree) 
  (5) It doesn’t matter what a person does-if the politicians want to listen, they will, and if they don’t want to listen, they won’t. (Disagree) 
  
B. *Output Efficacy*: 
  (1) The real political power in this country belongs to people like me. (Agree ) 
  (2) People who don’t vote throw away a good chance to choose their leaders and change public policy. (Agree) 
  (3) There are plenty of ways for people like me to have to say in what our government does. (Agree) 
  (4) It hardly makes any difference who I vote for because whoever gets elected does whatever he wants to do anyway. (Disagree) 
  (5) It doesn’t seem like public officials anywhere care much what people like me think. (Disagree) 

C. *Political Trust*: 
  (1) Most public officials are fairly smart people who usually know what they’re doing. (Agree)
  (2) A candidate’s ability is the most important thing in helping him win an election. (Agree)
  (3) It really doesn’t matter whether I get involved with politics because I know things will turn out pretty well anyway. (Agree) 
  (4,5,6) You can generally trust the government (in Washington, of Illinois, in my home town) to do what is right. (Agree)

"Future refinements of the input efficacy and political trust scales should, of course, be sensitive to be potential for response set effects which stem from the internally consistent direction-of-wording for these scales."

#---------------

Morrell, Michael E. 2003. “Survey and Experimental Evidence for a Reliable and Valid Measure of Internal Political Efficacy.” Public Opinion Quarterly 67(4): 589–602. doi:10.1086/378965.

@morrell2003

"(1) internal efficacy, which refers to the citizens' feelings of personal competence "to understand and to participate effectively in politics" (Craig, Niemi, and Silver 1990, p. 290)"

"(2) external efficacy, which refers to citizens' perceptions of the responsiveness of political bodies and actors to citizens' demands (e.g., Balch 1974; Converse 1972)."


#------------

Citation:
Miller, Warren Edward, Santa A. Traugott, and Santa Traugott. *American national election studies data sourcebook, 1952-1986*. Harvard University Press, 1989.

_Internal Political Efficacy_, indicates individuals self-perceptions that they are capable of understanding politics and competent enough to participate in political acts such as voting. [@miller1989, 254]

_External Political Efficacy_, unlike internal political efficacy, measures expressed beliefs about political institutions rather than perceptions about one’s own abilities. A sense of external efficacy denotes the feeling that an individual and the public can have an impact on the political process because government institutions will respond to their needs. The lack of external efficacy or the feeling of inefficacy indicates the belief that the public cannot influence political outcomes because government leaders and institutions are unresponsive to their needs. [@miller1989, 254]

And since I have the opportunity, here are the definitions for trust in government and government responsiveness;

_Trust in Government_ refers to the public’s basic evaluative orientation toward the government in Washington…The constructed index runs from high trust or confidence in government to distrust or political cynicism. Cynicism thus indicates a negative evaluation of government and reflects the belief that the government is not functioning in accordance with individual expectations of efficiency, honesty, and equity. [@miller1989, 253-254]

_Government responsiveness_ reflects beliefs about the extent to which specific political institutions (public opinion, parties, and elections) and leaders (Congressmen) can bring about responsive government...The resulting index ranges from low to high responsiveness, indicating the extent to which the respondent believes that the institutions mentioned will be effective in making government responsive to the needs of the people. The emphasis is on the responsiveness of political institutions rather than on the effectiveness of individual citizens. [@miller1989, 254]



#-----------



"Political efficacy is the belief that one has the skills to influence the political system." (Zimmerman 1989)



Zimmerman, Marc A. 1989. "The Relationship Between Political Efficacy and Citizen Participation: Construct Validation Studies." *Journal of Personality Assessment* 53(3): 554--66.





#--------------



Political efficacy, or "the feeling that one is capable of influencing the decision-making process" (Goel, 1980, p. 127)



Goel, M. L. ( 1 980). Conventional political participation. In D. H. Smith & J. Macaulay (Eds.), Participation in social and political activities: A comprehensive analysis of political involvement (pp. 108-1 32). San Francisco: Jossey-Bass.



Quoted in

McLeod, Jack M., and Dietram A. Scheufele. 1999. "Community, Communication, and Participation: The Role of Mass Media and Interpersonal Discussion..." *Political Communication* 16(3): 315.



#--------------



Sulitzeanu-Kenan, Raanan, and Eran Halperin. 2013. "Making a Difference: Political Efficacy and Policy Preference Construction." *British Journal of Political Science* 43(2): 295--322.

> "In many ways, political efficacy can be defined as people's sense of control over their public and personal environments through acceptable political processes." (Sulitzeanu-Kenan and Halperin 2013, 298)


From [source](https://www-cambridge-org.proxy-um.researchport.umd.edu/core/journals/british-journal-of-political-science/article/making-a-difference-political-efficacy-and-policy-preference-construction/16AAA3529D8B451CD4C1C313217C59FC)

#--------------

Abramson, Paul R. 1972. "Political Efficacy and Political Trust Among Black Schoolchildren: Two Explanations." *The Journal of Politics* 34(4): 1243--75.


> "*Political effectiveness* can be conceived as a norm, as a disposition to be effective, or as a behavior. One views efficacy as a norm when he says that persons should be able to influence political leaders. One conceives of efficacy as a disposition when he says that people feel that they can influence political leaders. And one views efficacy as a behavior when he discovers that people do, in fact, influence political elites." (Abramson 1972, 1244)

Every time I read this I can't help but think about how dumb this is.

> "As a concept, political efficacy appears in three separate although by no means independent guises: as a norm, as a psychological disposition or feeling, and as a form of behavior."

> "As a norm it refers to the timeless theme of democratic theory that members of a democratic regime ought to regard those who occupy positions of political authority as responsive agents and that the members themselves ought to be disposed to participate in the honors and offices of the system. The norm of political efficacy therefore embodies the expectation in democracies that members will feel able to act effectively in politics."

> "In recent years it has been the burden of considerable research to demonstrate that this democratic norm must entail a corresponding set of dispositions. If persons are to be able to live up to the norm and to bring their weight to bear effectively on the political process, we would hypothesize that they are more likely to be able to do so if they have become imbued with a sense of political efficacy. Here efficacy identifies a disposition towards politics, a feeling of effectiveness and capacity in the political sphere."

> "As compared with the simple statement of the norm, political efficacy as a feeling has turned out to be a surprisingly complex phenomenon. It suggests a number of interwoven sentiments. To be efficacious it would appear that a person must sense his competency at the level of his political self-identity. He must construct a psychic map of the political world with strong lines of force running from himself to the places of officialdom. He must come to believe that when he speaks other political actors will listen. He must also so internalize the expectation of competence that his political self- confidence is not easily eroded by what he will take to be the mistaken indifference which the political process frequently exhibits to his desires. The psychological counterpart to the basic regime rule, involving as it will the mutual expectations of the participating member and the responsive authorities, is therefore a firm conviction by the individual that he is in fact politically effective"


---------------------------

Muller, Edward N. 1970. "Cross-National Dimensions of Political Competence." *The American Political Science Review* 64(3): 792--809.


-   "Political efficacy, the belief that the ruled in a political system have some capacity for exercising influence over the rulers" (Muller 1970)


-   The concept of political competence, as formulated by Barnes, subsumes political efficacy under the aegis of an individual attribute consisting of "political skills plus the sense of efficacy necessary for effective political action"

  Samuel H. Barnes, "Leadership Style and Political Competence," in Lewis j. Edinger (ed.), Political Leadership in Industrialized Societies (New York: John Wiley and Sons, 1967), p. 60

------------------------------------------------------------------------------------------------

Kourvetaris, G A, and B A Dobratz. 1982. "Political Power and Conventional Political Participation." *Annual Review of Sociology* 8(1): 289--317.

-   "Citizens of a democracy tend to believe that their political participation influences the decision-making process. However, both citizen participation and influence on the electoral policy-making vary among individuals and groups. Differential political participation and influence are closely related to social inequality and political stratification in the American society in general." (Kourvetaris and Dobratz 1982, 303)

::: note
Note that the author presumes democracy as a given, i.e., "Citizens of a democracy...", implying the comparative beliefs of citizens not of a democracy. We know now that the people of most countries largely believe their country to be democratic regardless of regime type.
:::


------------

Iyengar, Shanto. 1980. "Subjective Political Efficacy as a Measure of Diffuse Support." *The Public Opinion Quarterly* 44(2): 249--56.

> "The sense of political efficacy also taps a fundamental principle in democratic regimes, namely, that political institutions and public officials be responsive to the preferences and needs of citizens^1^" (250)
    
>    ^1^ The sense of political efficacy includes "external efficacy"---perceptions of the regime as responsive---and "internal efficacy"---perceptions of the self as competent to influence government. The distinction between these dimensions is not to be taken lightly for as Balch (1974) has demonstrated, internal and external efficacy are divergently related to a number of criterion variables. In considering subjective efficacy as an indicator of diffuse support, we are clearly concerned with external and not internal efficacy.

--------------------------

Rudolph, Thomas J., Amy Gangl, and Dan Stevens. 2000. "The Effects of Efficacy and Emotions on Campaign Involvement." *The Journal of Politics* 62(4): 1189--97. doi:[10.1111/0022-3816.00053](https://doi.org/10.1111/0022-3816.00053).


> "The political relevance of citizens' affective judgments is increasingly becoming a target of scholarly inquiry. Marcus and MacKuen (1993) have demonstrated that individuals' affective judgments enhance the efficiency of information processing during presidential campaigns. Emotions, however, are uniform in neither their underlying processes nor their effects on political behavior. Marcus and MacKuen have argued that candidate-induced anxiety stimulates political learning but not campaign involvement. This study informs the analysis of emotions and campaign involvement by considering the moderating influence of political efficacy. Specifically, we demonstrate that internal efficacy moderates the influence of anxiety on campaign involvement. Anxiety among the highly efficacious drives involvement while anxiety among those with low internal efficacy is of little consequence. In short, we find that the extent to which negative affect influences campaign involvement is conditional, at least in part, on individuals' perceived ability to successfully undertake political action."

> "Self-efficacy theory anticipates an interactive relationship among self-referent thought, affect, and behavior (Bandura 1977, 1982). Self-efficacy, Bandura (1982) writes, can be characterized as "judgments of how well one can execute courses of action required to deal with prospective situations" (122). It is, at root, a self-appraisal of operative capabilities. Perceived self-efficacy affects the relationship between affective arousal and behavior. According to Marcus and MacKuen (1993), detection of threat creates feelings of anxiety which then inhibit ongoing behavior. Anxiety stimulates attention and learning rather than involvement. Bandura (1982) suggests, however, that "perceived self-efficacy operates as a cognitive mechanism by which controllability reduces fear arousal" (137). While anxiety alone may inhibit behavior, the interaction of anxiety and perceived self-efficacy should inspire greater involvement. In short, efficacious people are less likely to be inhibited by their anxiety and more likely to confront environmental demands by increasing their involvement"

> "Bandura's concept of perceived self-efficacy has been explicitly linked to the "internal" dimension of political efficacy (Madsen 1987).^2^ Internal efficacy is defined as "individuals' self-perceptions that they are capable of understanding politics and competent enough to participate in political acts such as voting" (Miller, Miller, and Schneider 1980, 253). It is a self-appraisal of political competence and capabilities"



> ^2^ The "external" dimension of political efficacy, or perceived system responsiveness, is represented by Bandura's (1982) concept of "response outcome expectations"

------------

Yeich, Susan, and Ralph Levine. 1994. "Political Efficacy: Enhancing the Construct and Its Relationship to Mobilization of People." *Journal of Community Psychology* 22(3): 259--71. doi:[10.1002/1520-6629(199407)22:3<259::AID-JCOP2290220306>3.0.CO;2-H](https://doi.org/10.1002/1520-6629(199407)22:3%3c259::AID-JCOP2290220306%3e3.0.CO;2-H).

> "Collective political efficacy is proposed as a third component of the political efficacy construct. This component represents perceptions of system responsiveness to collective demands for change. While the external political efficacy component represents perceptions of the responsiveness of the political system to the actions of individuals, this new component represents perceptions of system responsiveness when masses of people organize to demand change." (260)


## Internal Political Efficacy


## External Political Efficacy

