---
title: "digressions"
---

## 2025-04-17

Throughout U.S. history, political conditions have changed, sometimes quite significantly from what had been the *status quo* prior to. But as it relates to political efficacy, the political conditions that changed were not always conditions pertaining to the capacity of the people to shape the political environment. To be sure, many changes that pertain to the people *en mass* were ordained in order to prohibit and protect against arbitrary discrimination of one group or another, which no doubt contributes to the people's popular capacity. 

The subject, in this case, doesn't merely refer to one individual person, but to all those people who are equally subject to the same political conditions.

So when considering changes to the 'external' political environment that may relate to efficacy attitudes, consideration must be constrained to the conditions of the political environment that shape the people's popular capacity to shape that very same environment. That is to say, people are subject to conditions of the political environment, but what is of interest in regards to political efficacy is the capacity of the subject, in turn, to subject the political environment. 

To put in other terms, the popular capacity of the people to shape, change, reform, or otherwise constitute the conditions of their political environment is the basal purpose of engagement and participation within, and without, the political system. 


Political efficacy has been conceived as an individual's attitude in regard to themselves situated along two component dimensions, but the conception falters as soon as we move to consider the so-called 'external' dimension. In one dimension, political efficacy is conceived as one's personal confidence in their ability to merely encounter or confront political topics, issues, or affairs; internal political efficacy is no more than an individual's self-qualification as more or less politically competent. The conception of the other dimension, external political efficacy, immediately forgoes an appraisal of the individual's ability to do or accomplish or produce or 

## 2025-05-07

:::{callout.note}
This is stuff I'll likely just save for later. Gets a bit too in the weeds.
:::

External efficacy is most commonly referred to as "...beliefs about the responsiveness of governmental authorities and institutions to citizen demands" [@craig1990, 290; @niemi1991a, 1408]. It is understood as one component of a more general sense of political efficacy [@campbell1954], the other component being internal political efficacy [@morrell2003]. Research in the late 1980's and early 1990's focused on establishing a valid and reliable measurement for internal and external political efficacy [@craig1982]. In so doing, researchers formulated a reliable measurement scale for internal political efficacy but it remained unclear what external political efficacy measures really captured [@niemi1991a]. Indeed, studies that included external efficacy items conducted common factor analysis to either validate a robust measurement instrument for *internal* efficacy [@niemi1991a], or aimed to disentangle external efficacy from political trust in various forms [@craig1990].  In a note, @niemi1991a states that the two items meant to capture external efficacy "...are tapping something quite different from the new efficacy questions....whatever they do measure...they *do not* measure internal efficacy" [-@niemi1991a, 1412, italics in original]. Despite this ambiguity, it is rare to find critical research or scholarship directly focused on examining the meaning and measure of external efficacy. Rather, external efficacy serves as more of a blank slate with which measurements are developed instrumentally to serve the ends of a particular research agenda.

Quite often, researchers acknowledge the difficulty in simply understanding political efficacy as it concerns external efficacy by pointing to inconsistent or conflicting findings of previous research. However a common palliative is to conceive of a nuanced sub-conception of political efficacy either distinct from, or complimentary to, the commonplace understanding while not departing too far from the shoreline. Sometimes this takes the form of slightly modifying the standard question/statement wording or adding in novel questions/items to establish a unique measurement and narrowed conception of efficacy [@phoenix2024; @wolak2018]. Or new dimensions are added to the overarching notion of political efficacy to coincide in tandem with, yet distinct from, the internal and external dimensions of political efficacy [@gildezuniga2017; @lee2006]. Thus a slew of unique renditions of external political efficacy grow within the literature, only to inherit the same feeble conceptual foundation^[This is not limited to political studies of opinion and behavior; novel, conflicting, or sometimes redundant, efficacy constructs emerge and proliferate across many disciplines. [see @skurka2023; @hamann2024]]. 

Since the measures of external efficacy have not sufficiently validated the construct as conceived, then it isn't really clear what is being measured in the first place. However, the responses to measurement items have consistently been shown to be inter-correlated with each other and weakly influenced by some underlying common factor. The issue is that the only thing confirmed about this underlying factor is that it, "...appears to represent something other than feelings of internal efficacy" [@craig1982, 96].

So, external political efficacy is difficult as it is not entirely clear what, exactly, is being measured. Especially in relation to other similar hypothetical constructs^[Note the distinction between a hypothetical constructs and a concept] such as trust in government and perceived government responsiveness. External efficacy is too easily conflated with these two at the conceptual level, but has at various times been shown to be somewhat distinct by way of common factor analysis methods. The idea seems to be that the survey items are measuring something distinct enough, so external efficacy should continue to be measured as a relatively distinct homogeneous construct. The problem, again, is that there's not a clear and concise notion as to what the survey items are actually measuring. In other words, responses to the two survey items appear to be influenced by some underlying factor distinct, but related to, similarly conceived political constructs, but there isn't enough for researchers to distinguish a cogent concept in theory that could be referred to as external political efficacy^[Note the common issue in factor analysis known as the 'naming fallacy'. Just because a factor is given a name doesn't mean that is what influences the various indicators (i.e., survey item responses)].

A bigger issue is that even if additional survey items were developed and showed sufficient influence from a common underlying factor, this would only validate the conception of external efficacy insofar as the wording of the survey items and corresponding responses conclusively linked to its contemporary conceptualization in the literature. 

# 2025-05-16

Previous research has already demonstrated that changing the rules significantly effects voter turnout, participation, vote choice, and the like [@ang2019]. The question is whether particular efficacy beliefs are concurrently impacted. That is, we would expect efficacy beliefs to shift when the rules change; especially those rules pertaining to the people's capacity to effectuate change in their political environment through government and politics. If the measurement instruments in use are sound, then we're better able to determine whether, and to what extent, public attitudes are sensitive or insensitive to actual shifts within the political environment. However, if the measurement instruments in use are not sound (invalid), then credibility of our conclusions are dubious at best.

To put in other words, the event here is the ruling in Shelby County v Holder which empowered state governments to change voting laws without need for preclearance from the federal government. so across the different states, voting laws changed or did not change. The question is whether changes in laws that pertain to popular efficacy stimulate efficacy beliefs *in general* as measured by external political efficacy measures. 

So to be clear, the aim of this study isn't to determine whether changes to voting laws influence external efficacy *per se*. Rather, the aim of this study is to determine whether the meaning and measurement of external efficacy is sound. If the shifts in external efficacy are not significantly related to changes to political conditions (such as voting laws), there are two potential interpretations: either attitudes/beliefs are insensitive to changes in the political environment or the measurement instrument in use is unable to measure the attitude of interest. We can only suppose the former is the case insofar as we are confident that the measurement of the construct is sound. However, multiple studies over time have noted inconsistencies [] and efforts to validate the meaning and measure of external political efficacy are not only sparse but throw a substantial amount of doubt on the validity of the measurement. Moreover the conceptual understanding of external efficacy is hardly distinguishable from government responsiveness, which is further complicated by such strong relation to political trust (trust in government). In fact, early literature attempting to disentangle the conceptual ambiguity refers to external political efficacy as the "responsiveness component" and "perceived responsiveness" [@craig1979]. 

Yet if it happens to be the case that shifts in external efficacy are not related to changes in political conditions, the most damning evidence against the implication that attitudes/beliefs are merely insensitive to changes in the political environment is the evidence showing that significant changes in political behavior can be attributed to, or associated with, changes within the political environment. We may be able to detach political behavior from having a necessary relationship with attitudes; attitudes don't necessarily cause political behavior. Yet it is untenable to consider that shifts in the environment, which subsequently spur changes to political behavior, won't also elicit some shift or development of relevant attitudes. 

The problem with external political efficacy, or political efficacy as it is understood generally, is that nothing seems to account for an upward shift in efficacy despite significantly substantive changes of political conditions in history common to the public writ large. When reviewing average scores of the external efficacy index over time, a steady decline in external efficacy begins from its height in 1960 ($73.5$) downward to 2020 ($28.5$), with yet unexplained spikes and dips from 1984 to 2002. Although comparison shows that higher levels of average external efficacy in the aggregate are most prominently distinguished by educational attainment over time, there is a clear decline despite changes that expanded or further enabled the public to shape the political environment by the means available during the Civil Rights Era. When distinguishing by race, average external efficacy among White non-Hispanics is considerably higher compared to Black non-Hispanic throughout the extent of external efficacy's history of measurement^[I don't think there's an issue with breaking down the trend by race, seeing as how the ANES includes weights so as to be representative of the national population]. However, simply reviewing the external efficacy index does not hint that any dramatic political changes regarding public capacity came about during the era in which the Voting Rights Act (VRA) was enacted and repeatedly affirmed.

In particular, the Voting Rights Act incorporated monumental change in the political environment that affected all subject to that same environment in common^[Perhaps technically speaking, the VRA changed the political environment by serving as an act "[t]o enforce the fifteenth amendment to the Constitution of the United States, and for other purposes.". Ratified in 1870, the fifteenth amendment had already explicitly prohibited government from denying or abridging the citizen's right to vote on account of race, color, or previous condition of servitude. Although prior laws were in place that included provisions intended to guarantee voting rights, the VRA of 1965 conditioned the capacity of state governments to deny or abridge voting rights by imposing criminal penalties for violation of the law, subjected state governments to federal oversight of voting laws, and directed federal intervention to guarantee voting rights.]. Although the extent of what the people could do (i.e., could produce or bring about as governors) didn't change, the conditions shifted to restrain governing actors of the many states from incapacitating whole swaths of the public from participation in the endeavor. Such change in political conditions directly relates to the people's capacity to shape the political environment given the changes pertain to the means of popular political production (even if it is limited to electing persons into official government positions).

The point is not that we would expect to see shifts in political efficacy or external efficacy to be most prominent among Black people or other racial or ethnic minorities during or sometime after this time period. Rather, the point is that levels of external efficacy in the aggregate clearly decline despite changes where we would expect otherwise. Especially as the effect of the VRA on voter turnout and registration was immediate and dramatic in the years following 1965. However, under a conceptual definition of external efficacy seemingly interchangeable with government responsiveness and on par with political trust, the decline in 'external efficacy' as measured seems a bit more reasonable. This is apparent in @converse1972's early conjecture listing common events during the 1960's which, to him, appeared somewhat obvious as influential on the decline of political efficacy,

> "It is not hard to imagine what some of these events were during the 1960's, although specific items on any list would produce somewhat different impact in various segments of the electorate. A list should undoubtedly include the three shocking political assassinations in 1962, 1967, and 1968; the perception in some small but articulate quarters early in 1965 that Lyndon Johnson, after winning a landslide vote for his campaign against Goldwater's proposals to escalate the war, immediately had turned himself to escalating that war; resentment in other larger sectors of the population concerning official pressures toward school desegregation, particularly after 1964; race riots and campus disorders from 1965 on; and throughout, the increasing weariness and frustration with the bleeding war in Vietnam that the government could not seem to win or otherwise terminate. This sequence of national catastrophes, disruptions, and blunders seems adequate *to account for a considerable loss of confidence in the government and politics on the part of the public*. Nor is there much doubt that the decline of efficacy is functionally related to the weakening in sense of partisanship after 1965, which was discussed earlier." [@converse1972, 330, italics added]

Note that, while this small list can't account for all that was eventful during the 1960s, this list of events is indicative of how political efficacy---in particular, external political efficacy---was and has been understood *as an evaluation of government performance*. Converse refers to these events as "national catastrophes, disruptions, and blunders", yet the relation to efficacy in any sense of the word is not clearly explicated. How or why political assassinations would impact or relate to political efficacy is not obvious, at least not to me. In my view, this should have no impact on an appraisal of people's capacity to shape the political environment. Nor does the President's behavior in office concerning campaign promises made. However, if the meaning of 'efficacy', political or external, refers to satisfaction with government performance, then the short list offered by Converse does come off as a somewhat reasonable---though idiosyncratic---explanation for declining efficacy levels over time.       

(and this is my contribution I think) The conceptual understanding of external efficacy is too far removed from the meaning of efficacy to make sense as its own concept.    

The relation of political trust and political (or external) efficacy is, I think, due to the circumstance of the political system and regime type. Trust is requisite when powerless. Power, to be clear, denotes a condition of (having) possibilities for action and representing those possibilities as such. When the capacity to bring about a preferred outcome is unavailable to the one who prefers it, then they must rely on empowered others to take action and bring about preferred outcomes in their stead. Political trust is apt considering the regime type of the United States where a scheme of representation is in place. The actions and outcomes of politics and government are divorced from direct popular control. Those elected to office are vested with the power of government for the purposes outlined in the Preamble to the U.S. Constitution. 

As such, there is a degree of uncertainty that arises from the empowerment of the branches of government. Indeed, there is always uncertainty in the realm of possibility---when possibilities for action are present before actors. Even if the power of the people was explicated as being equal, or superior, to the branches of government and actors therein, there would still arise uncertainty with respect to the power of government and the relations of power. However, if the power of the people were on par with the power of governing actors, concerns over the loss of trust in government would be far reduced from what they are today and have been. Thus, the substantive significance and concern for the public's trust in government is itself an indicator of the relations of power between the people and their government.

Trust concerns how others will act provided the possibilities for action present before them, in particular, whether empowered others will act in accordance with some preference or stipulation. The public's trust of whether those vested with the power to govern the state will purpose their actions toward common ends.

The key difference between political trust and political efficacy must be that the latter is more relevant to appraisal of a state or regime as democratic, whereas the former is not relevant. A lack or absence of political trust in a political system wherein the popular capacity of the people is on par, and ultimately superior to, those agents vested with authority to govern bears no relevance as to the status or regime type of the political system. Of course, high levels of political trust writ large and in general is probably healthy and preferred, but trust is not necessitated due to the relations of power among the people and governing actors. Whatever disfavored acts that government takes is possible for the people to rectify by means of their popular self-governance; sufficient mechanisms of accountability in place render political trust of government a nice privilege but not necessary. In contrast, in a political environment wherein the people's popular capacity is stunted, restrained, or simply notional by the means present within the political system and processes, then a sufficient degree of political trust in government seems necessary to pacify the subjected populace.

# 2025-05-27

Political efficacy arose instrumentally as a concept for researchers aiming to explain political behavior. In other words, the concept of political efficacy was invented merely as a tool to explain political behavior---an explanation of behavior based on, or in, the psychology of the individual. Although behavior isn't always coherent with attitudes, nor is it simple to conclude that one's behavior is primarily driven by their attitudes, it is harder to deny links between behavior and the environment. A link without which the field and study of economics cannot do. 

:::{.callout-note}
2025-05-29, the following is a short little digression that I didn't relate back to the paragraph above.
:::

The link between behavior and attitudes is far more troublesome, as the assumptions of traditional economic theory---i.e., rationality and self-interest---fail to hold on observation of human behavior in relation to conditions of the environment. Behavioral economics focuses on studying the failures of these assumptions by developing models of behavior consistent with findings from psychology. In particular, behavioral economics incorporates cognition into studying the link between environment and behavior. Incorporating cognition incorporates the study of how humans reason, process information, acquire knowledge, hang on to knowledge, and the like. Thus, what is found in the discipline are concepts and theories related to heuristics, or mental shortcuts, biases, patterns, modes, and methods of thought and the effects thereof on decision-making and judgement; mostly with reference to some deviation from logic into fallacy. 

As such, behavioral economics stops just short of being a disciplinary field focused on the study of opinions, opinion formation, sentiment, attitudes, or simply, beliefs, although there is much overlap and relation. Conditions of the environment are understood as affecting cognition which is doubtlessly connected with behavior in one way or another, thus affirming the link between environment and behavior through cognition. But attitudes are somehow their own beast not wholly detached from any of these but also not necessitated by any of them either. Although the relation is readily apparent, the link is ultimately less clear between attitudes and behavior, the environment and attitudes, and the interconnection between the environment, attitudes, and behavior. Even the coherence between cognition and attitudes is fugitive. A person's cognition may be observed as responsive to the environment, which may help to explain this or that behavior, but an attitude can be studied in much the same way while observed as independent from the particular behavior, and sometimes even seemingly independent of cognition itself. Simply put, attitudes are weird. 

Attitudes are something like fickle conclusions, evanescent in nature. Attitudes are sometimes settled after some cognitive process spurred on by environmental stimuli, or sometimes not. A resulting attitude can be wildly incoherent from, while still significantly related to, contextual stimulus and subsequent cognition. Or sometimes attitudes are seemingly not the result of any conceivable cognitive process or rationale, yet still vary from being weakly held and transient, to strong, intense, and stable over time. 

Previous research has already demonstrated that changing the rules significantly effects voter turnout, participation, vote choice, and the like [@ang2019]; changes to the political environment affect subsequent political behavior. The question is whether particular efficacy beliefs are concurrently impacted. That is, we would expect efficacy beliefs to shift when the rules change; especially those rules pertaining to the people's capacity to effectuate change in their political environment through the processes of government and politics. If the measurement instruments in use are sound, then we're better able to determine whether, and to what extent, public attitudes are sensitive or insensitive to actual shifts within the political environment. However, if the measurement instruments in use are not sound (invalid), then credibility of our conclusions are dubious at best.

To put in other words, the event here is the ruling in *Shelby County v Holder* which empowered state governments to change voting laws without need for preclearance from the federal government. so across the different states, voting laws changed or did not change. The question is whether changes in laws that pertain to popular efficacy stimulate efficacy beliefs *in general* as measured by external political efficacy measures. 

So to be clear, the aim of this study isn't to determine whether changes to voting laws influence external efficacy *per se*. Rather, the aim of this study is to determine whether the meaning and measurement of external efficacy is sound. If the shifts in external efficacy are not significantly related to changes to political conditions (such as voting laws), there are two potential interpretations: either attitudes/beliefs are insensitive to changes in the political environment or the measurement instrument in use is unable to measure the attitude of interest. We can only suppose the former is the case insofar as we are confident that the measurement of the construct is sound. However, multiple studies over time have noted inconsistencies [] and efforts to validate the meaning and measure of external political efficacy are not only sparse but throw a substantial amount of doubt on the validity of the measurement. Moreover the conceptual understanding of external efficacy is hardly distinguishable from government responsiveness, which is further complicated by such strong relation to political trust (trust in government). In fact, early literature attempting to disentangle the conceptual ambiguity refers to external political efficacy as the "responsiveness component" and "perceived responsiveness" [@craig1979]. 

Yet if it happens to be the case that shifts in external efficacy are not related to changes in political conditions, the most damning evidence against the implication that attitudes/beliefs are merely insensitive to changes in the political environment is the evidence showing that significant changes in political behavior can be attributed to, or associated with, changes within the political environment. We may be able to detach political behavior from having a necessary relationship with attitudes; attitudes don't necessarily cause political behavior. Yet it is untenable to consider that shifts in the environment, which subsequently spur changes to political behavior, won't also elicit some shift or development of relevant attitudes. 

The problem with external political efficacy, or political efficacy as it is understood generally, is that nothing seems to account for an upward shift in efficacy despite significantly substantive changes of political conditions in history common to the public writ large. When reviewing average scores of the external efficacy index over time, a steady decline in external efficacy begins from its height in 1960 ($73.5$) downward to 2020 ($28.5$), with yet unexplained spikes and dips from 1984 to 2002. Although comparison shows that higher levels of average external efficacy in the aggregate are most prominently distinguished by educational attainment over time, there is a clear decline despite changes that expanded or further enabled the public to shape the political environment by the means available during the Civil Rights Era. When distinguishing by race, average external efficacy among White non-Hispanics is considerably higher compared to Black non-Hispanic throughout the extent of external efficacy's history of measurement^[I don't think there's an issue with breaking down the trend by race, seeing as how the ANES includes weights so as to be representative of the national population]. However, simply reviewing the external efficacy index does not hint that any dramatic political changes regarding public capacity came about during the era in which the Voting Rights Act (VRA) was enacted and repeatedly affirmed.

In particular, the Voting Rights Act incorporated monumental change in the political environment that affected all subject to that same environment in common[^1]. Although the extent of what the people could do (i.e., could produce or bring about as governing actors) didn't change, the conditions shifted to restrain governing actors of the many states from incapacitating whole swaths of the public from participation in the endeavor. Such change in political conditions directly relates to the people's capacity to shape the political environment given that the changes pertain to the means of popular governance (even if it is limited to electing persons into official government positions).

[^1]: Perhaps technically speaking, the VRA changed the political environment by serving as an act "[t]o enforce the fifteenth amendment to the Constitution of the United States, and for other purposes.". Ratified in 1870, the fifteenth amendment had already explicitly prohibited government from denying or abridging the citizen's right to vote on account of race, color, or previous condition of servitude. Although prior laws were in place that included provisions intended to guarantee voting rights, the VRA of 1965 conditioned the capacity of state governments to deny or abridge voting rights by imposing criminal penalties for violation of the law, subjected state governments to federal oversight of voting laws, and directed federal intervention to guarantee voting rights.

The point is not that we would expect to see shifts in political efficacy or external efficacy to be most prominent among Black people or other racial or ethnic minorities during or sometime after this time period. Rather, the point is that levels of external efficacy in the aggregate clearly decline despite changes where we would expect otherwise. Especially as the effect of the VRA on voter turnout and registration was immediate and dramatic in the years following 1965. 

However, under a misconceived definition of external efficacy---seemingly interchangeable with government responsiveness and on par with political trust---the decline in 'external efficacy' as measured seems a bit more reasonable. This is apparent in @converse1972's early conjecture listing common events during the 1960's which, to him, appeared somewhat obvious as influential on the decline of political efficacy,

> "It is not hard to imagine what some of these events were during the 1960's, although specific items on any list would produce somewhat different impact in various segments of the electorate. A list should undoubtedly include the three shocking political assassinations in 1962, 1967, and 1968; the perception in some small but articulate quarters early in 1965 that Lyndon Johnson, after winning a landslide vote for his campaign against Goldwater's proposals to escalate the war, immediately had turned himself to escalating that war; resentment in other larger sectors of the population concerning official pressures toward school desegregation, particularly after 1964; race riots and campus disorders from 1965 on; and throughout, the increasing weariness and frustration with the bleeding war in Vietnam that the government could not seem to win or otherwise terminate. This sequence of national catastrophes, disruptions, and blunders seems adequate *to account for a considerable loss of confidence in the government and politics on the part of the public*. Nor is there much doubt that the decline of efficacy is functionally related to the weakening in sense of partisanship after 1965, which was discussed earlier." [@converse1972, 330, italics added]

Note that, while this small list can't account for all that was eventful during the 1960s, this list of events is indicative of how political efficacy---in particular, external political efficacy---was and has been understood *as an evaluation of government performance*. Converse refers to these events as "national catastrophes, disruptions, and blunders", yet the relation to efficacy in any sense of the word is not clearly explicated. How or why political assassinations would impact or relate to political efficacy is not obvious, at least to me. In my view, this should have no impact on an appraisal of people's capacity to shape the political environment. Nor does the President's behavior in office concerning campaign promises made. However, if the meaning of 'efficacy', political or external, refers to satisfaction with government performance, then the short list offered by Converse does come off as a somewhat reasonable---though idiosyncratic---explanation for declining efficacy levels over time.


The question at the heart of the issue is whether external efficacy is responsive to changes in the political context. 

The reason this question arises is because the meaning of the concept is divorced from the meaning of 'efficacy', conflated with government responsiveness, and far too easily confused with trust in government. Adding to this conceptual ambiguity, the measurement of external political efficacy offers no clarity and results from measurement lend little credence to construct validity. Only two items are utilized to construct an index, which itself is inadequate to consider as a measure of some homogeneous construct. 

The conventional, or standard, definition of external efficacy boils down to be understood as an individual's evaluation of government performance, composition, or behavior. Results of measurement might merely reflect one's satisfaction with government generally, though interpretation is easily construed in whatever way most convenient to the researcher. Indeed, external efficacy readily stands as an individual's evaluation of past government performance, but it just as easily stands as an individual's impression of government favor, or similarly, of system responsiveness to public input, or of government officials receptiveness to public preferences. 

For the two decades covering the 1950s and 1960s, @converse1972 noted that education, political attentiveness, and activism all closely correlated and increased together across time, whereas in contrast there was a general decline in the classic feelings of political efficacy as measured during that period [-@converse1972, 334]. Noting this divergence, Converse, as others, strove to decompose political efficacy into two distinguished components.

> "As implied at several points, it is useful conceptually to partition gross feelings of political efficacy as we have measured them over the years into at least two components, which might he more precisely labeled "personal feelings of political competence" and "trust in system responsiveness." The first term refers to the individual's sense of his own fundamental capacities and experience in operating in a political domain. The second refers to perception of properties of the political system as it stands at a point in time." [@converse1972, 334].

The deconstruction of political efficacy into two dimensional components was asymmetric.
Reading between the lines here and elsewhere in the literature impresses the idea that the goal of separating political efficacy into internal and external conceptual constituents was to parse out a construct that aligned suitably well with education, interest, attentiveness, and other characteristics based on individual-differences. The internal efficacy component mends well with these personal characteristics as a useful political correlate or function of them. 

There's a significant qualitative difference, however, between the explication of the first term and the obscure abstraction of the second. Indeed, "trust in system responsiveness" not only blends trust in government and government responsiveness into the external component, but is vaguely described as referring to a "perception of properties of the political system". Which properties? What kind of perception, exactly? That being said, Converse discusses an important point,

> "Although the distinction is easily made at a conceptual level, it is much more difficult to make empirically, for there are obvious causal interactions between the two terms. Moreover, *the sheer definition of personal skills that are politically effective is to some degree dependent on the shape of the political system itself, and most specifically, the kind of influence attempts to which it is open, if any*." [@converse1972, 334, italics added]

The evolution of internal efficacy has rendered its construal as one's personal confidence to competently confront political topics, affairs, or issues by measure of their general understanding and self-qualification in comparison to most other people in general. So feeling like one can personally be "politically effective" today largely rests on one's self-appraisal of their knowledge and understanding of politics. Yet Converse states that the requisite skills that are *in fact* politically effective is dependent on the shape of the political system itself, and importantly, "...the kind of influence attempts to which it is open, if any." 

Notable is the underlying notion that some set of individual personal skills are necessary for one to be politically effective. Converse, like others before and after him, afford special weight to an ideal model of citizenship; a citizen that is active, interested, well-informed, and otherwise engaged in the domain of government and politics is, and has been, modeled as the most efficacious since the conception of the term. Yet this contradicts the idea of political equality, where the input of one is no more or less than that of another of equal status. So if the shape of the political system is such that the status of each individual is politically equal---meaning equally subject to the law and so empowered---then individual differences such as personal skills are politically irrelevant. Unless the shape of the political system is such that unequal weight is provisioned to individuals of a certain class, caliber, group, or some other status distinction. Converse follows with an imaginary example to illustrate the distinction between the internal and external components while also noting the importance of the political context,

> "Imagine the articulate and gregarious individual with great organizational expertise transplanted from a democratic setting where he has employed his capabilities in party organization with high success to a dosed and heavy-handed authoritarian regime. The transplantation would not have affected his skills and, ideally, measurements should show a high sense of political competence but a low estimate of system responsiveness. However, most ways of assessing the individual's own sense of political competence would be inadvertently influenced in such a situation by limitations on skills that could plausibly achieve a political response in his immediate setting." [@converse1972, 334]

The setting---i.e., conditions of the political environment---are paramount in regard to political efficacy of any sort. What Converse seems to assume, however, is that for *democratic settings* a particular set of political skills, such as party organization capabilities, best contribute to one's capacity to produce responsiveness from government in return. 

Efficacy is inherently tied to the end for which some thing or act is purposed. Converse here makes clear that being effective means successfully influencing or being influential in some way in government and politics. Inherent to the notion of political efficacy is the underlying purpose of participating in the political process of whatever system. Implied here by Converse, and by authors everywhere else, is that the purpose of individual or popular political participation is ***to influence*** the actors and institutions of government. Therefore, it is conveyed by implication that *the maximum effect achievable through political activity* is but merely to influence governing actors of the political regime.

The core problem is that there is not a clear way to validate the construct as defined and understood because it is not defined well enough to be understood as a distinctive construct.

# 2025-05-30

:::{.callout-note}
Another digression...
:::


It is easy to set the agenda (so to speak) as to what stimulus government, in general, would expectedly be most responsive due to the underlying normative element here regarding representative government. That is, its easy to convey one's normative considerations about that which *should* stimulate government response as that which *is expected* to stimulate government response *in accordance with theory*. Considering the underlying political theory differs with respect to models of representation (e.g., the 'trustee' versus 'delegate' model), as well as differing normatively, it is important to clarify what government is responding to. 

Whether the government *should* be responsive to majority opinion, versus simply being stimulated by that which is in the people's *best* interests, versus responsibly addressing that which is in the people's *common* interest, are all easily blended by vague terms and phrases. Simply put, it is easy to neutralize a normative distinction between "public needs" and "public wants" by the use of vague language in the conceptual definition. For instance, evaluating the extent to which government is responsive to "public demand" is vague about what is meant by "public demand". Surely, the term could refer to mass public opinion, or perhaps more precisely, majority opinion; but the term could also refer to that which is in the "best interests" of the public. 

This problem would seem strictly a concern for pedants except that the difference in meaning comes across through the variety of definitions of external efficacy. Both @craig1990 and @neimi1991a made reference to "citizen demands" in the definitions of external efficacy as, "...beliefs about the responsiveness of governmental authorities and institutions to citizen demands" [-@craig1990 290; -@niemi1991a, 1408]. Whereas @miller1989 refers to government responding "to their needs" [-@miller1989, 254]. An alternative to the use of vague language is to simply include both meanings, which @iyengar1980 did when referencing the holistic sense of political efficacy, "...that political institutions and public officials be responsive to the *preferences and needs* of citizens" [@iyengar1980, 250, italics added]. Doing this, however, doesn't resolve the issue of what stimulus we would expect government to be responsive to in theory. 

One might appeal to the 1st amendment to the U.S. Constitution which explicates the right of the people, "...to petition the Government for a redress of grievances." Taking "redress" to mean 'to remedy', 'rectify', 'compensate', etc., the responsibility of government is to take action to remove the cause of whatever grievance or complaint, or otherwise provide relief upon petition. However, this only shifts the problem on to clarifying what it means to petition the government.

Outside of the right to petition the government for resolution of legal disputes, to petition the government for a redress of grievances has been reduced to (or made coterminous with) *expression* (i.e., speech) as held by the Supreme Court, "Petitions are a form of expression..." (*Borough of Duryea V. Guarnieri* 564 U. S. 379 2011). 

> "Both speech and petition are integral to the democratic process, although not necessarily in the same way. The right to petition allows citizens to express their ideas, hopes, and concerns to their government and their elected representatives, whereas the right to speak fosters the public exchange of ideas that is integral to deliberative democracy as well as to the whole realm of ideas and human affairs. Beyond the political sphere, both speech and petition advance personal expression, although the right to petition is generally concerned with expression directed to the government seeking redress of a grievance." *Borough of Duryea V. Guarnieri* 564 U. S. 379 (2011) 

Petitions to causes of public concern are definitely acknowledged as a meaningful form of expression, and the court weighs much, if not all, of the emphasis on petition *as a right* of the people.

> "Petitions to the government assume an added dimension when they seek to advance political, social, or other ideas of interest to the community as a whole. Petition, as a word, a concept, and an essential safeguard of freedom, is of ancient significance in the English law and the Anglo-American legal tradition." *Borough of Duryea V. Guarnieri*, 564 U. S. 379 (2011) 

> "The right to petition is in some sense the source of other fundamental rights, for petitions have provided a vital means for citizens to request recognition of new rights and to assert existing rights against the sovereign." *Borough of Duryea V. Guarnieri*, 564 U. S. 379 (2011)

However, when it comes to the function of petitioning the government for redress, earlier opinion of the Supreme Court made clear that petitioning the government for redress does not necessarily require or mandate government response in the form of redress.

> "Nothing in the First Amendment or in this Court's case law interpreting it suggests that the rights to speak, associate, and petition require government policymakers to listen or respond to individuals' communications on public issues." 
*Minn. Bd. Commun. for Colleges v. Knight*, 465 U.S. 271 (1984)

Although the court has referred to the right to petition as a means, *the efficacy of said means is limited to the ends of public expression*. Outside of elections, petitioning the government through litigation is formalized as a direct means of inducing government response. However even then, it must be said, petition via litigation is mediated by the judiciary.

> "Individuals may also “engag[e] in litigation as a vehicle for effective political expression and association, as well as a means of communicating useful information to the
public.” *In re Primus*, 436 U. S. 412, 431 (1978). Litigation on matters of public concern may facilitate the informed public participation that is a cornerstone of democratic society. It also allows individuals to pursue desired ends by direct appeal to government officials charged with applying the law." [@borough2011, 397]


## 2025-08-06

> “Alternatively, a strong sense of internal efficacy indicates to that individual that he or she possesses the means to secure a response from government officials, even when those officials generally are unresponsive to the demands of other citizens.” [@craig1982, 86]

Note that this is in reference to *internal* political efficacy. The "means" here are those of which that are "internal" to the individual, i.e., that which refer to the individual's personal capacity. Importantly, an individual evaluates their own internal capacity---with respect to those "internal means"---in comparison to other people. So inherent to the conception of internal efficacy is the focus on an individual's skill or proficiency---*with respect to the enabling faculties of their person*---compared in reference to their perception of the general capacity of other people toward the same end. Internal efficacy is, indeed, simply a measure of one's own capabilities compared to the same of most others. But what is important is the inherent focus on those *means* which are inextricably “*internal*”, i.e., the personal faculties of the individual which enable their competency in the pursuit.

Yet, even more important to recognize are the stated **ends** to which one's personal political endeavors aim---to "secure a response from government officials". Whatever that means is hardly ever explicated in the literature, save for a section within the seminal "Civic Culture".

So an individual evaluates their own internal capacity to secure a response from government in comparison to the general internal capacities of others.

Note also that the internal efficacy items don’t ask an individual to rate themselves on a particular set of skills or evaluate some particular set of personality traits or individual differences. The reason is likely because researchers would first need to establish exactly which traits, skills, attributes, or characteristics are most successful toward the endeavor. These traits would need to be wholly independent from any external context, resource, privilege, status, or other condition, and rest upon *political efficacy solely attributable to an individual’s personality*. However, such traits cannot be identified. Not because we lack the methodology to determine them, but because no such traits exist. 

A boisterous and bold political character may be enough to influence politicians or be effective as a campaign manager for a certain political party at one point in time, but those same characteristic traits may render one otherwise impotent in the next. Researchers of earlier epochs in survey research whom were interested in political behavior referred to political participation as campaign involvement, party membership, and meeting attendance. The competency of the political participant was tied to a particular character archetype. The participant of yesteryear would likely find the political environment of today utterly foreign. 

The political environment is dynamic for this very reason. There is no such trait or set of traits for participatory competence just as there is no gene for human success. The political environment changes strictly because the humans who constitute it are forever varied and ever changing.

As such, the standard survey items purported to measure internal political efficacy have an individual evaluate general qualities of themselves in comparison with most other people. In fact, the first item has an individual self-assess their own qualification to simply participate in politics.  

1.    "I consider myself well-qualified to participate in politics" [SELFQUAL]
2.    "I feel I have a pretty good understanding of the important political issues facing our country" [UNDRSTND]
3.    "I feel that I could do as good a job in public office as most other people" [PUBOFF]
4.    "I think that I am better informed about politics and government as most people" [INFORMED; 1988 and after]

Whatever one considers in response to these statements, it seems clear that knowledge and understanding of the topic or domain are the key elements that drive one's impressions of their own competence confronting topics or otherwise engaging in that domain. And it makes sense that political researchers, whom are themselves highly educated and well aware, regard knowledge as power, or at least the way in which one feels competent.

If we suppose that the key elements embedded in the scale of internal political efficacy are indeed aspects such as knowledge, information, understanding, awareness, and the like, then it makes sense that internal efficacy is strongly associated with educational attainment. The analysis of @converse1972 becomes more potent. The items are self-assessments of one's capacity to simply confront political topics and thereby engage in the domain of politics and government. The end to which these "internal means" function contribute to one's confidence to confront and engage as a participant---i.e., to *act*. 

Internal efficacy is not an appraisal of the efficacy of political actions, because one evaluates internal aspects of themselves. In short, a person evaluates their individual faculties which enable their competence as a political actor. Enlightenment and understanding of political issues, of contemporary affairs, or of the make and method of politics and government are implied as *'internal' means* necessary to function *competently* as a political actor. This does not imply, however, that greater knowledge and understanding enable the capacity to function as a political actor. Knowledge, understanding, and enlightenment are undeniably unnecessary for people to function as political actors. One's capacity as a political actor is not endowed by their knowledge or awareness, which in turn makes knowledge and awareness irrelevant to their competence as a political actor. Said in reverse, competence is not a necessary condition of one's capacity to function as a political actor.

But this goes further, as knowledge and awareness does not increase, heighten or bolster in anyway one's capacity to function as a political actor above others. Competence, in the sense of internal efficacy, pertains to the outcome of one's confrontation with political issues, affairs, and so on. One's capacity to function as a political actor is equal with others subject to the same political context. This is why the most important aspect to consider in regard to the *efficacy* in political efficacy are the *means* and the *ends* to which someone, something, or some act aims.

Now, internal political efficacy is a metric by which researchers assess the extent to which a person assesses their own competence to participate. Simply, a self-appraisal of personal political competence to confront topics and engage within the domain of politics and government. A person may confront political topics in conversation with a neighbor, a friend, or in some discussion through social media. They may also confront political topics or issues through various media such as books, film, television, the news, and so on. 

The extent to which they demonstrate competence upon such confrontation is partially a function of their knowledge and awareness of the domain in question. Another factor is likely their implicit evaluation of most other people, which is then referenced in the comparison with themselves. And of course other factors may be their level of interest or familiarity. 

But what it means to "demonstrate competence" when confronted with whatever political issue or topic is not unambiguous. The individual has their own criteria for which to evaluate political competence in the abstract, and thus the internal efficacy items record an individual's assessment of their own personal political competence to participate "effectively". 

The meaning of "efficacy" in internal political efficacy has been confused with "competence". According to this confused meaning of "efficacy", greater levels of internal efficacy denote greater levels of personal political competence. And to researchers, competence is driven by knowledge and awareness.

Greater levels of internal political efficacy are associated with political participation---be it higher frequency of engagement in particular activities or more experience in a greater number of different activities, whatever they may be. Internal efficacy can predict engagement. Educational attainment is associated with internal efficacy. 


It is worth emphasizing that a person evaluates their own *competence* and not specifically the extent to which they feel *capable*; their capability is implied. Additionally, this evaluation of themselves is made with respect to most others (whom are also implied as capable), even though only two of the survey items make the comparison explicit.

## 2025-08-06

When did scholars truly "buy in" to this two-dimension distinction between internal and external political efficacy? I think probably since @converse1972 explicitly affirmed the theoretical distinction upon review of the performance of the classic political efficacy items across time. 

Timeline:

-   Seminal book by @campbell1954 titled "The Voter Decides" introduced the construct and initial measure of political efficacy which they believed was related to political activity. These authors referred to this variable as "sense of political efficacy" which they defined as "...the feeling that individual political action does have, or can have, an impact upon the political process, i.e., that it is worth while to perform one's civic duties."
    > "Sense of political efficacy may be defined as the feeling that individual
    political action does have, or can have, an impact upon the political
    process, i.e., that it is worth while to perform one's civic duties. It is
    the feeling that political and social change is possible, and that the
    individual citizen can play a part in bringing about this change."
    [@campbell1954, 187]

-   @lane1959a 

-   Perhaps starting in the early 1970s, the original SRC (or CPS, I guess) political efficacy scale came under intense scrutiny. In particular, the validity and reliability of the scale as well as the reliability of each item as adequately contributing to measurement of the homogeneous construct. 

-   1972: @converse1972 writes forever about the inadequacy of the original scale and provides an analysis summarized very well by @mcpherson1977, 
  > "Converse found that three of the four items in the SRC efficacy scale
  significantly increased during the 1950s then significantly decreased in the
  1960s, while the other showed a continuous increase between 1952 and 1968.
  More detailed analysis indicated that these  aggregate statistics
  substantially understate the instability of efficacy feelings because
  individual changes cancelled each other out to a significant degree." [@mcpherson1977, n3]
  
-   1974: @balch1974 essentially breaks ground by supplying empirical support for the long-standing idea that political efficacy is a two-dimensional concept. Balch conducts a ‘multiple item analysis’ where he examines the correlations between items of political efficacy and other external variables. He concludes that ‘sense of political efficacy’ is actually best understood as two distinct aspects (or components): the external and the internal. He’s more loose with the connection of both to a singular concept of political efficacy, as he suggests that theories on either aspect can be linked or correlated but not one-in-the-same. 

-   1979: Drawing upon earlier literature, @craig1979 initiates early attempts to empirically disentangle the two-dimensional components of political efficacy as well as separate each from political trust by testing new measurement items. 

-   1980: Under the notion that a proper interpretation of the Gamson hypothesis is that the prospect for popular action is enhanced when citizens regard themselves as competent political actors, @craig1980 makes the argument that "The absence of a valid and reliable measure of internal efficacy has precluded a fair test of the Gamson hypothesis." [-@craig1980, 195]. The manuscript for the eventual publication by @craig1982 had already been drafted, as noted by Craig in a footnote.

-   1982: @craig1982 stresses the need to develop alternative measures to account for the two component conceptual distinction of political efficacy. They demonstrate the inadequacy of original CPS political efficacy battery, and stress the need for alternate measures to operationalize the conceptual internal and external distinction

-   1987: NES conducts pilot study including 35 old and new efficacy and trust items with the intent of improving upon traditional measures while retaining continuity of measurement over the years. 

-   @craig1990 detail the results of the 1987 NES pilot study, reporting results from confirmatory factor analysis that support the two dimension distinction. However while the internal efficacy battery of items was recommended for inclusion in subsequent NES surveys, the authors recommended that additional indicators for external efficacy should be developed and that response options other than the simple agree/disagree format should be put into use in order to reduce problems caused by response set. The only eventual change to the external efficacy items, however, was the expansion of response options from the simple agree/disagree binary format to a response scale that included "Neither agree nor disagree" as the center option.

-   1988: NES deploys the four newly revised internal efficacy items while retaining three of the original CPS efficacy items, two of which comprise the standard external efficacy items. The response options of all items are now expanded to include a middling "Neither agree nor disagree" response option. 

-   @niemi1991a report results that validate the new internal efficacy scale as a measure of a distinct and homogeneous hypothetical construct. However it is noted throughout that the external efficacy items were "considerably less impressive" but nevertheless "adequate for the task of evaluating the external validity of our four-item internal efficacy battery." [@niemi1991a, 1411]. The most that is stated about the measures for external efficacy is that, "...whatever they do measure...they do *not* measure internal efficacy" [-@niemi1991a, 1412, emphasis original].


So in 1982, Craig and Maggiotto publish an article showing the inadequacy of the original measurement items of political efficacy, and stress the need for new measures to codify the theoretical distinction between the internal and external components of political efficacy. The article essentially breaks apart the common measure for political efficacy into at least two dimensions, and calls for the development of *valid and reliable* measures for each dimension.

Fast forward to 1987, NES conducts a pilot study to test a whole swath of new efficacy and trust items, which results in the 1990 report by @craig1990 supporting the two dimensional conceptual framework of political efficacy. @craig1990 report on the results of the pilot study that tested five separate scales: internal efficacy, incumbent-based external efficacy, regime-based external efficacy, incumbent-based trust, and regime-based trust (or diffuse support). The authors conclude,

> "Taken as a whole, the pilot study results strongly support the notion that major changes are needed in the way we operationalize such concepts as political efficacy and political trust." [@craig1990, 307]

Importantly, the report advises that the **internal political efficacy** battery tested should be used in future NES surveys as it "...would correct a major flaw in the original political efficacy scale", whereas additional indicators of external political efficacy "...should probably be developed" [-@craig1990, 307]. Today, however, only two items are used to compose the external political efficacy index and these two items remain virtually unchanged from the original "sense of political efficacy" measurement scale introduced by @campbell1954 in "The Voter Decides".

The 1988 NES survey included the four new internal political efficacy survey items, but retained three of the original items from the Center of Political Studies (CPS) political efficacy scale, two of which comprise the current common measure for the supposed external dimension of political efficacy:

1.    People like me don't have any say about what the government does. [NOSAY]
2.    I don't think public officials care much about what people like me think. [NOCARE]

Versions of the items according to the ANES CDF codebook

1952-1988, and 1992:

I don't think public officials care much about what people like me think."

1990, 1994-Later:
Public Officials don't care much what people like me think.

2000 TELEPHONE,2002:
Do you agree, neither agree nor disagree, or disagree with this
statement?

# 2025-08-15

### Conceptual ambiguity, unrestrained interpretation, and the conceptual canvass

Over time, the conception of external efficacy went from explicit conflation with responsiveness of government to an empirically demonstrated distinction from perceived government responsiveness [@esaiasson2015]. Despite the continued march into conceptual obscurity, the items meant to measure external political efficacy have remained virtually unchanged. 

The conventional, or otherwise, 'standard', definition of external political efficacy is conflated with government responsiveness and difficult to parse from trust in government. The expectation that external efficacy should shift in response to changes in the political environment doesn't necessarily follow from a conception of external efficacy as referring to "...beliefs about the responsiveness of governmental authorities and institutions to citizen demands" [@craig1990, 290; @niemi1991a, 1408]. Even when considering additional clarification regarding what survey items intend to measure and what low or lacking external efficacy implies, conceptual focus and operative measurement is based on the perceived responsiveness of governing officials and institutions.  

> "[External efficacy] measures expressed beliefs about political institutions rather than perceptions about  one's own abilities .... The lack of external efficacy . . . indicates the belief that the public cannot influence political outcomes because government leaders and institutions are unresponsive to their needs" [@craig1982, 86]

-   @craig1982 referenced the following definition of external political efficacy adopted by the Center of Political Studies (CPS) by 1980^[Note the excerpt was derived from the 1989 edition of the American National Election Studies Data Sourcebook. I was unable to locate the earlier 1980 edition cited in @craig1982].

> “External Political Efficacy, unlike internal political efficacy, measures expressed beliefs about political institutions rather than perceptions about one’s own abilities. A sense of external efficacy denotes the feeling that an individual and the public can have an impact on the political process because government institutions will respond to their needs. The lack of external efficacy or the feeling of inefficacy indicates the belief that the public cannot influence political outcomes because government leaders and institutions are unresponsive to their needs.” [@miller1989, 254]

This excerpt states that external efficacy denotes the feeling that the public can have an impact because of the presumption that government will respond to their *needs*, not their demands or some other form of engagement or input. That is, it states that a response from government is induced by simply having particular needs for the government to address---not by actively doing anything to arouse government into action. This particular definition, in essence, seems confused with trust in government---the individual trusts that the government will aim to benefit the public’s best interest, acting accordingly in response to the needs of the public.

Note that this understanding diverges considerably away from having to do with 'efficacy' at all. The individual believes that the public "can have an impact" because government "will respond to their needs". It is not understood as a belief about the efficacy of public input, and in fact @miller1989's conception removes public input from the idea. Public *needs* aren't necessarily conveyed via some form of public input---by overt expressions or explicit demands or the like---but may be recognizable from observation. Whatever the public needs is not tenable as a means of any kind. In short, the conception of external efficacy espoused here refers to a belief regarding whether, and to what extent, the government responds to the needs of the public. An evaluation of the influential capacity of 'public needs' may be an evaluation of efficacy sure enough, insofar as 'public needs' can be objectified in noun form and denoted as a stimulus. This is the same as evaluating the efficacy of hunger towards influencing another to feed the hungry. But this is not *necessarily* an evaluation regarding the efficacy of the means of public input (e.g., public activity) aimed at influencing or stimulating government response to address public needs.

In earlier work, @craig1979 gave a nuanced conceptual distinction between **political trust** and external efficacy[^1], where political trust, "...refers to government action perceived as being more in the public interest than as a product of popular demand." [@craig1979, 229]. The distinction is slim but based on whether one believes government efforts are for the sake of the public interest, distinct from the extent to which one believes government action is stimulated by popular political activity. Note, however, the judgement of either political trust or external efficacy is based on one's abstract impressions about the motives, considerations, and goals of actors in government.

[^1]: External efficacy was referred to as "*Output (external) efficacy*" in @craig1979, described as, "...the degree to which an individual perceives his political actions as being (potentially) successful. This introduces the notion of responsiveness, and is the dimension conceptually closest to that of our traditional understanding  of the efficacy concept" [@craig1979, 229]

Thus, it is hard to validate the expectation that external efficacy would shift upon changes to the political environment based on understanding of the concept expressed in the literature; the expectation doesn't follow from its conceptual definition. The political environment is not interchangeable with government responsiveness in meaning nor metric. Indeed, the very moniker of the construct as "external political efficacy" seems incoherent with its stated meaning.


# 2025-08-22

one, perhaps, logical issue here is that the efficacy of voting---a means of political production---remains unchanged. An individual's vote is equal to the votes of all others who actually do vote, and the impact of their votes still effectively determine whatever elections are meant to determine. It is *the efficacy of the means* that ordain and establish the people's popular capacity to shape the political conditions of which they are also subject. 

Every election only a portion of those eligible to vote do so. Of course, this may be very well related to the cost of voting, or it may not as citizens who are eligible to vote are at liberty to vote or not vote. Whatever the case, the votes in an election, however few, still result in an electoral outcome; the outcome is no less diminished with a lower turnout. Rather the effect of the vote is to determine the *direction* of the outcome; whether candidate A is elected over candidate B; whether some state proposition is endorsed by a majority; whether or not a state constitution is amended as proposed, and so on. An outcome will come about regardless, it seems, but it isn't clear generally whether the people's participation is at all necessary. 

A hypothetical that seems a bit ridiculous is "what if no person voted?" Answers to that question are perhaps easily given, at least in terms of the general election to decide the U.S. President. The voters don't decide who becomes President anyway, so the answer in that case becomes moot. There may be an urge to refer to state procedures to break an electoral tie, but this is insufficient and speaks more to the necessity of the public. Nothing and no one is elected if no person casts a vote, so there's no tie to speak of. 

The idea that the state legislatures or Congress would decide as though breaking a tie is an admission that, simply, another election would be held among a smaller proportion of the people who designate themselves as the authority. In other words, this is an admission that the people's intervention is simply not necessary to continue the functions of government; an admission that the political system and regime type is and has been an oligarchy. Therein lies a criterion of popular rule---the necessity of the people's pursuit to rule themselves. It seems quite obvious now and speaks to the point made before that the purpose of popular political activity is always to rule---to shape---the conditions in which the people are subject. If no person votes but the political system carries on without but a murmur, then it was never close to democratic in the first place. 

Those who are elected to government office are not somehow detached from the body politic, and they gain no special status empowering them to choose in the absence of a popular choice. Those elected to public office are elected for a particular term, and so when those terms end, those people are resigned from political office. Ironically, all those who abstained would still be responsible for their self-government. In fact, this responsibility is always on the shoulders of the people as a popular collective, no mater the political system in place or governing regime. When the people are not, nor cannot, be held responsible for their government and politics, then its simply not a democracy. Ought implies can.

It seems to me that this is but one way in which the government dissolves: starvation.  



This is the definition of power---a modal category of having possibilities for action and representing those possibilities as such [@parietti2022]. The act of voting is at the disposal of the individual. However something is limited in this idea that simply having the power to act is enough to convey the meaning of power proper with respect to the power of the people; it seems to forego the potency of the act itself. 

# 2025-08-26

NOTE: I wrote the first paragraph the other day, but I copy it over here to address some thoughts

One, perhaps, logical issue here is that the efficacy of voting---a means of political production---remains unchanged. An individual's vote is equal to the votes of all others who actually do vote, and the impact of their votes still effectively determine whatever elections are meant to determine. It is *the efficacy of the means* that ordain and establish the people's popular capacity to shape the political conditions of which they are also subject. 

The difficulty in constructing a set of survey items (questions) that have respondents evaluate the efficacy of the means is that we are having them evaluate the means with its intended function or broader purpose. So, for example, by having someone evaluate the efficacy of voting, the end must be explicated. However, the purpose some act, the end, can range from being quite broad or narrowly specific. 

For instance, we drink water in order to survive; the end explicated here is 'to survive', and so drinking water is but a means to that end. A water fountain facilitates our means to achieve this end. Yet I can frame the end a bit differently and thus distance the end sought from a broader, overarching end. For instance, we drink water in order to hydrate our bodies, or otherwise said, to ensure adequate hydration of our bodies. Hydration is the process of replacing water within our bodies, which is necessary for our bodies to function. Again, stated otherwise, we drink water to ensure continuous function of our bodies. Of course, ensuring "continuous function" of our bodies is an odd way to express the same sentiment as "to survive". So one might rephrase this end sought as "to ensure the *healthy* function of our bodies". Then, eventually, the phrase describing the end sought is shortened to simply "to ensure our health". Thus, "we drink water to ensure our health". This is a slightly different statement from "we drink water to survive" even though the end is ultimately the same, the connotation differs slightly. Health is a quality of our survival, or rather, of being alive. So by simply changing the end, the purpose of drinking water as "to ensure our health" or even as "for our health", there's a subtle shift from a definitive end-state---being alive----to a qualitative one---being more or less healthy, but nevertheless alive.

A slight difference in connotation is not the bigger issue, however. We may explicate the end sought by drinking water in regard to one of its particular functions within our bodies. The process of hydration is itself a term that glosses over the particular roles that water serves within our bodies. So one might assert that "we drink water in order regulate our body temperature", and we know that regulating our body temperature is vital for our continued survival. But the point is that the statement asserts the end as "to regulate body temperature" rather than "to survive", therefore creating further distance between the overarching purpose of drinking water from the particular function the act serves. An intermediary supplants the ultimate purpose of the act.

It is incredibly important to clearly explicate the end sought by the means in question. When it comes to the act of voting, its easy enough to supplant the point of the endeavor with the function of an election or refer to the particular dilemma the election is meant to resolve. For instance, stating that the point of voting is to elect persons into government office, or to approve or reject propositions put to referenda, is unobjectionable because these are true statements. However, the issue is that the overarching, broader purpose of voting in elections is put at a distance and made evermore abstract such that it becomes symbolic. In order to make this putative purpose explicit, we then need to ask follow up questions that would explain why people are elected into government or why governing propositions are referred to the people for resolution. These are not simple inquiries and readily lead us down paths aiming to explain why something happens rather then clarify the point of the endeavor.

Why do we drink water? To stay hydrated. Why do we need or want to stay hydrated? To survive. 

So you might explain that the people vote in elections to elect other people to serve in government office so those people can do the job of governing the state of the people. And you might explain that the people vote in elections to resolve dilemmas of governing referred to them. But the point is easily missed, and even easier to omit. Why do we elect others into government office? To govern. Why do we resolve dilemmas referred to us by voting? To govern. The point, the purpose, is for the people to govern the state of the people. This is always the point of political activity, regardless of political system or regime type. Not all may be considered or classified as political actors but all political activity aims toward the same end: to govern conditions which encompass the state of the people. 

The term "to govern" is kind of a broad and ambiguous term itself. To be clear, the act of governing refers to shaping the conditions of which the people are subject. Or otherwise stated, government shapes conditions which encompass the state of the people. I'll note here that I refrain from referring to 'government' as an entity as is often the case elsewhere. It is common to speak of "the Government" as an entity in reference to the body of persons holding principal political offices in tandem with the cumulative set of institutions 

:::{.callout-note}
The following stemmed from what I started above but ended up being only somewhat related.
:::

Why are others elected to govern? The answer here is can be, at once, pragmatic as well as philosophical, or one of either. In the pragmatic sense alone, the people *writ large* are unable to govern directly due to the simple fact that there are too many people in the population to congregate into a cohesive and functional governing body. Not to say that it is impossible because there has been such self-governing collectives in history, but with respect to the modern age, a practical way for all the people as political equals to conduct and administer the government of themselves is yet to be conceived and attempted. 

There are many other philosophical answers to the question that have been written or professed, many ancient and some modern. These answers to the question "Why are others elected to govern" provide a normative stance that explains why the people *should* elect others to govern the state of the people. This isn't to say that such normative philosophies are not ever reasonable, but simply that one is often required to accept certain predicate assumptions or assertions as true in order to accept such normative philosophical answers to the question. 

One answer to the question has come in various forms overtime, but what is held in common across the variety of philosophical perspectives is that people, in general, or on average, or by their nature are inadequate, or ill-suited, or ill-equipped, or unworthy, or simply unable to govern conditions in which they are subject as a collective. Certain views establish that governing requires a particular set of skills or virtues that of which are not uniformly distributed to each individual in the populace, and therefore concluding that the role of governing *ought* to be assigned to those who merit qualifications for the role. This view may be ancient but is subscribed to by many today. 

Of course, this leads me to the kind of answer that, in a certain way, is disingenuous to the question posed. This is the kind of answer that refutes the premise that the people themselves are not self-governing. The act of voting to elect others to government office is what establishes the people as self-governing in fact. This answer is defended even though the structure, form, and processes of the political system define the possibilities available to the people as detached from the possibilities available to those who govern the state of the people. That is, to the question "why are others elected to govern?" the answer professes that others being elected to govern is no different from the people governing themselves as a collective body. In order for this to be true one must accept certain philosophical propositions as true, especially those regarding the capacities afforded given the structural conditions and processes of the political system. 

It is the philosophical propositions about elections that serve as the basis for view. Accordingly, it must be accepted that a people who elect a smaller subset from their population to governing office is, in fact, the act by which they govern themselves. Collective self-governance is achieved through that smaller body of officials by virtue of the election itself.

Another, perhaps more modern, version of the aforementioned "*merit*" view is that certain requisites are not necessarily endowed to some by nature but are developed through adequate education and socialization. This more modern view still suggests that some are just best fit for the role as it prescribes particular requisite characteristics for the individual and the self-governing society *writ large* as criteria, but it doesn't discriminate who has potential to meet this requisite criteria. The differences between individuals are, then, paramount to consider, promote, and nurture given an assumption of people in general as naturally unqualified for the role. Something notable about this view is that it regards this *fitness* as readily attainable for each individual, and by extension feasible for society as a whole to attain as ideal, given a predicate assumption of the political system and processes therein. That is, the view already accepts as true by assumption that the capacity of the people to collectively self-govern political conditions is fully afforded by the given conditions of the state in which they are subject. The fundamental assumption is that the conditions of the state completely facilitates the means available for the people to govern said conditions. The efficacy of the political activity itself is uninhibited by conditions of the state, and as such, the effect of political action is always maximized for the individual who participates. Thus to explain current conditions of the state and government thereof, this view orients us to focus on individual differences among the people.




## 2025-09-09


-   So early on, @balch1974 conducted a multiple-item analysis where he examined the correlations between items thought to correspond to the classic 'sense of political efficacy' with "external" variables such as political interest, political knowledge, (conventional) political participation, political trust, and a variable construct referred to as "propensity to engage in protest behavior". The political efficacy items were already distinguished into the internal and external pairs in theory, and so Balch examined the inter-item correlations accordingly. 

-   The interesting thing to me is that separate theories for the relations between each set of items had to be proposed for each external variable examined against the items of political efficacy. It had to be stated whether the inter-item correlations for one pair of items were expected to be positive or negative according to some reasonable theory as did for the other pair of items. Really, the goal was to determine whether the pairs of items "behaved" differently when correlated with items from the external variables. For some relationships, the items were expected to be both positively correlated, but one pair would display stronger correlation than the other pair. In other cases, the pairs of items were expected to diverge into positive and negative correlations, respectively. But in the case of  

-   The (conventional) political participation scale ('propensity toward conventional participation') consisted of six items asking three questions: whether they would, and whether they have, engaged in three particular behaviors. a) contacted a politician, b) attempted to persuade another to vote in a different direction, and c) work for a candidate. 

> "The variable in the literature most consistently and centrally related to sense of political efficacy has been conventional political participation. This is the last aspect of political involvement to be confronted with data here. Respondents were asked whether they (1) would, and (2) have actually attempted to, engage in three acts in the national political arena: (a ) contact a politician , (b ) convince someone to vote in a different direction, and (c) work for a candidate. These six items and the scale of propensity toward conventional participation (derived through summating responses on the items , corrected for unequal response categories ) are correlated with the efficacy items and scale in table 5."

Balch finds that internal efficacy items support the notion that "high efficacy accompanies high participation", but seems perplexed at the low and lacking correlation for what would become the external efficacy items.

> "The pair A items support the widespread research finding that high efficacy accompanies high participation. But the pair B items yield very weak positive correlations with participation and several apparent non-correlations. A closer look at the pair B items shows that they have almost no correlation at all with reported behavior, as distinguished from behavioral propensity. Only if the pair B items were to correlate negatively with conventional participation would their validity as indicators of political efficacy be more suspect."

What is interesting is this implicit criteria that Balch mentions in brief; if the external efficacy items (pair B) were negatively correlated with the conventional participation items, then their "validity as indicators of political efficacy" would be more suspect. These item correlations are dismal for the external efficacy items, but the 'conventional participation' items are hardly sufficient themselves. The external efficacy items correlated highest with "Would you contact a politician" (NOCARE = 0.10, NOSAY = 0.18) and "Would you work for a candidate" (NOCARE = 0.12, NOSAY = 0.14) 

> "In only two cells does the efficacy scale yield higher correlations than for each of its items; the effi cacy scale represents its target concept less fully than do the items."

> "The second pair of items (pair B) yields zero correlations and low correlations in both directions, suggesting their possible invalidity as indicators of "sense of political efficacy. They even show a negative relationship with political information. The political involvement scales correlate more strongly than do their component items with all of the indicators of efficacy except the doubtful pair B items."

The reason why this is interesting is because in the next section, Balch examines the efficacy items against the other participation variable, referred to as the "*propensity to protest*". 

-   This *propensity to protest* variable was an index comprised of four items that asked essentially two questions twice: 1) would they march peacefully around an area, 2) have they marched peacefully around an area, 3) would they boycott classes or products, 4) have they boycotted classes or products. 

> "Respondents were asked whether they (1) would march and (2) have marched peacefully around an area and /or boycotted classes or products. These four items and the index of demonstrative participation (which is their sum, corrected for unequal response categories) are correlated with the efficacy items..." [@balch1974, 17]


By implication, Balch distinguishes participation into two categories: the conventional (say, Orthodox) form of political participation and the unconventional form. This "unconventional" form is not explicitly stated as such, but it is characterized in the paper as "regime-challenging" according to the literature referenced. The literature synthesized by Balch at this time appeared to have strong normative impressions with respect to how they viewed protest activity. In particular, such activity is juxtaposed with support for regime-challenging demagogic politicians, whereas the considerations of political efficacy lead to exceptions that the 'efficacious' individual would not nor had not engaged in protest, perhaps as a matter of normative principle. This permitted Balch to examine political participation in two different categories under two implied normative considerations.

I note this because of the likened similarity with a separate paper that also examined political efficacy, specifically external efficacy, around the same time [@coleman1976]. In brief, the study by @coleman1976 makes some interesting hypotheses that expect external efficacy levels to differ according to social class, i.e., between upper and lower classes, but more importantly their hypothesis revolve around receptiveness to "symbolic outputs" of the governing one-party regime (in Mexico). Those who are expected to be "efficacious" are associated with the character of those in "pluralist" regimes such as England, West Germany, and the United States.

The authors are explicit in that they consider Mexico, at the time, to be an authoritarian nation-state ruled by a dominant one-party regime. The emphasis of the paper is that the regime expresses many appeals to "symbolic desiderata" such as, "..."Social Justice," "Democracy," and a continuing commitment to the "Goals of the Revolution"..." [-@coleman1976, 196], and it is expected that the *lower classes* of this authoritarian regime are the ones most receptive to this kind of empty symbolism. Importantly, those who are most receptive to this kind of symbolic expression from the authoritarian regime, "...are also likely to see their regime as responsive. Those who see their regime as having slackened in its commitment to the revolutionary ideals are likely to see that regime as unresponsive." [@coleman1976, 196].

Said in other words, the lower class poor people of Mexico---denoted explicitly as an authoritarian context---are the one’s who are more inclined to associate the regime with symbols favorable to the popular ideals and values.

> "The lower class can be expected to be most receptive to these symbolic outputs by virtue of being those most [deprived] of material rewards in a system Where political bargaining over distributive questions is strongly discouraged. As a result, lower class Mexicans probably have greater psychic investments in believing that (a) the future will be better and (b) the regime is responsive, than would upper class Mexicans. Mexicans, while not necessarily rejecting the symbolic outputs, will make their assessments of external efficacy more in response to concrete outputs than will lower class respondents." [@coleman1976, 197]

To summarize, the theory proposed by @coleman1976 was that external efficacy is determined by *satisfaction with perceived symbolic ideology of governing regime*[^2], which they referred to as “cognitive symbol association”. The “symbolic outputs” that the authors discussed aren’t explicated very well, but can be understood simply as “lip service” to ideals and values prominent among the public, and such lip service was theorized to be most receptive to the poor, or lower class, of Mexico City. The upper classes, in contrast, were not expected to be so uncritical of government performance, instead having the better sense to base their evaluation on the more concrete material benefits outpouring from government.

> "The dominant factor in explaining external efficacy is clearly the receptivity of each citizen to the government-generated symbolism of the Mexican Revolution. Those who are receptive to the symbolism of the "Institutionalized Revolution" generally believe that the regime responds to citizens; those who reject the symbolism also tend to reject the notion that the regime is responsive to citizens." [@coleman1976, 201]

Although they don't find support for the hypothesis regarding differences between upper, middle, and lower classes, there is something notable about making that hypothesis in the first place with respect to this paper. To put simply, disregarding the class distinctions for the moment, those who fully "buy into" the *symbolic ideological alignment of the governing regime* are those who are found to report higher levels of external political efficacy[^1]. Their theory distinguished between the affluent and lower classes, juxtaposing a delineation between authoritarian and "pluralist regimes"[^3]. The theory paired lower class with authoritarianism as much as it did affluence with pluralism, and accordingly, expected external efficacy of the lower classes to be far higher than that of the more affluent. This exaggeration, however, was not supported. Instead, it appeared as though the symbolic outputs of the authoritarian regime is generally well received across all class distinctions. The message being that a regimes expressed adherence and commitment to symbolic ideals engenders a populace who feels satisfied with the responsiveness of government. 

When we take a comparative look at the way in which @balch1974, and literature he references, 



[^1]: Note that there are glaring issues with the items used to compose the external efficacy variable in this paper by @coleman1976. That being said, the two core external efficacy items (i.e., NOSAY and NOCARE) are included in the survey measurement. 

[^2]: @colman1976 do not phrase it in these words. This is merely my paraphrase of their overall theory and conclusion.

[^3]: Such cases of "pluralistic" regimes are stated as cases of England, West Germany, and the United States. So, "pluralist" in this sense stands in to subsume the usual democratic moniker. 



Critically speaking, this variable obviously doesn't reflect one's "propensity" but rather their expressed willingness and reported behavior. 


# 2025-10-29


## An argument favorable to the multidimensional conception of political efficacy

The conceptual delineation of political efficacy into two dimensions is supported by the notion that the dimensions pertain to the different conditions imposed upon the means available to the political actor. That is, that which conditions the efficacy of the means available to the political actor are delineated into two distinct, but weakly related, dimensions. 

One dimension of political efficacy is conditioned by that which is internal to the individual---e.g., impressions of their own knowledge, awareness, and esteem with respect to politics. The considerations of that individuals have about themselves as qualified, informed, and generally capable political actors delimits conditions of the "internal" dimension. Importantly, the internally efficacious individual views themselves as capable of competently confronting politics and government.

To be clear, this internal dimension concerns *efficacy* only in the sense that an individual appraises their own *capacity to do or achieve some goal*. According to the conceptual definition of internal efficacy and (operationalization of) the purported measurement items, the implied goal is *to competently engage in politics*, but no more than that. As such, the individual evaluates their perceived political competence in terms of their capacity to confront political topics, issues, and prospects of active engagement. 
This conception of the internal dimension, however, has been improperly distinguished from the external dimension in past literature. For instance, @craig1982 asserts, 

> “Alternatively, a strong sense of internal efficacy indicates to that individual that he or she possesses the means to secure a response from government officials, even when those officials generally are unresponsive to the demands of other citizens.” [@craig1982, 87]

This assertion doesn't cohere with the professed understanding and measure of internal political efficacy. One's internal efficacy is, simply put, a self-assessment of one's own competence *to confront and engage with political topics and considerations*. This self-assessment is a compared against one's impressions about the general political competence of the public writ large. The notion of internal efficacy cannot be understood as a sense indicating to the individual that they *possess* the (internal) means "to secure a response from government officials..." simply because this is 1) not in accordance with the given conceptual definition, and 2) incoherent with the meaning implied by the internal efficacy item statements. Upon review of the internal efficacy item statements, **it does not follow** that one's self-assessment of their "internal means" (i.e., of one's political competence) is "to secure a response from government officials". At best, agreement with the item statements lead to the interpretation that, in comparison with most other people in general, the individual believes theirself competent enough to engage with and consider political topics, affairs, or issues when confronted.

-   If internal political efficacy refers to a person's self-evaluation of their ***competence*** as an individual political actor to confront political topics and prospects of engagement, then external political efficacy would refer to a person's appraisal of the efficacy of active engagement to influence the outcomes of the political process and shape conditions of the political environment.

-   It is vital to understand that one's judgement of their own political competence is determined by *internal conditions*, otherwise understood as individual differences; internal efficacy is a certain kind of self-esteem conditioned upon various internal factors such as level of education, personal confidence, political interest, knowledge of political affairs, government processes, and so on.

-   In contrast, one's judgement of their own capacity as a political actor is determined by the external political conditions in which they are subject on par with other political actors of common status. Thus, one's appraisal of their own external political efficacy must directly reference the extent of their own capacity 1) as a political actor 2) to shape conditions of the political environment 3) as determined by the very political conditions in which they are subject. 

-   This appraisal of external efficacy is made of themselves as a political actor which is also necessarily an appraisal of all political actors subject to the same conditions (hence "People like me"). Thus, when a person evaluates their capacity as a citizen, they necessarily evaluate the capacity of all citizens of equal status strictly because said evaluation is not based upon individual differences, but rather based on that in which they do not differ: the conditions of their common status. Thus, in the first sense, external efficacy is best understood as an appraisal of their capacity to shape the political environment as actors subject to political conditions of that environment.

-   But there's more to it than that, as this isn't to say that the status of citizenship renders all citizens of equal capacity to shape the political environment. Citizenship is merely used as an example to illustrate the point. Indeed, the status of citizen does not necessarily guarantee equal conditions placed on one's capacity. For one, many citizens in the United States are incapacitated by their disenfranchisement in accordance with laws of a particular state. For two, many citizens of the United States who reside in non-state territories are unable to engage or participate in the governance of the political environment in which their citizenship pertains. In fact, the right of citizens to vote is not constitutionally protected considering that the United States constitution very meekly prohibits the United States or any State from denying or abridging the right of citizens to vote on account of particular conditions. For instance, the fifteenth amendment prohibits denial or abridgment of the right of citizens to vote on account of race, color, or previous condition of servitude---but not on current condition of servitude. As such, felony disenfranchisement is a commonality. 

-   This is worthy of emphasis: the capacity (to shape the political environment) of the individual as a political actor does not differ from other political actors who are all subject to the very same conditions. 

-   Where internal efficacy is a metric of one's self-assessed competence based on their individuality, external efficacy is one's appraisal of the public's capacity to shape the political environment under conditions which they share in common as subjects.

-   Common to both dimensions of political efficacy is the common purpose, or point, of political participation and engagement, which is ultimately to shape the conditions of the political environment. Prominent research and scholarship of yesteryear has unwittingly, but detrimentally, constrained the whole point of engagement and participation to imposing influence on the considerations of government officials. That is to say, previous scholars have stated that the point of participating in the political process is, at most, meant to influence those political actors who govern rather than to govern as political actors. Regardless of the political system or regime type, the purpose of political action is to shape the political environment and conditions thereof.



