---
title: "malformed-purpose-written-2024-08-15"
date: "2024-08-15"
---

:::{.callout-note}
I wrote the following on August 15, 2024. Today (2025-08-19), I would do what all writers do and re-edit all that I wrote again and again, but the text below is copied verbatim from when I wrote it a year ago. I have refrained from editing this here, so this document serves as an honest record. I will later revise what is written only to remove redundancy and improve clarity in a different document. 
:::


An important quote by V.O. Key,

> "And even in the least democratic regime opinion may influence the direction or tempo of substantive policy. Although a government may be erected on tyranny, to endure it needs the ungrudging support of substantial numbers of its people. If that support does not arise spontaneously, measures will be taken to stimulate it by tactical concessions to public opinion, by the management of opinion, or by both." [@key1961, 3]

> "The ethical imperative that government heed the opinion of the public has its origins, thus, in democratic ideology as well as in the practical necessity that governments obtain the support of influential elements in society." [@key1961, 4]

Support of influential elements in society is a practical necessity, but the imperative that government heed the opinion of the public is merely an ethical imperative, or in other words, unnecessary. What slips by unnoticed is what Key said a long time ago: public opinion is not necessary. Not for the operation of government; not for the determination or execution of governing policy, law, and regulation. This isn't to suggest that public opinion is not important, nor that it has had no place in the shaping of policy and other government outputs. The point, rather, is that public opinion is to government outcomes as prayer is to fate. The maximum effect of public opinion on the outcomes of government and politics is to influence those who govern. This is the efficacy of public opinion; not to govern but to influence governors. This point is similarly conveyed by Almond and Verba,

> "In all societies, of course, the making of specific decisions is concentrated in the hands of very few people. Neither the ordinary citizen nor "public opinion" can make policy." [@almond1963, 180]

Yet often the efficacy of public opinion supplants the unknown/undetermined efficacy of popular political participation. More so than that, the very definition of political participation is often confined to the maximal effect of public opinion--to *influence* government agents and outcomes thereof. Consequently, the purpose of popular political activity is so too constrained. The role of the citizen in a democracy is relegated (assigned/banished to a place of insignificance), and thus, the very conception of democracy shifts from *collective self-governance* [@ober2017] to ideal government responsiveness to majority expression.

Public opinion is professed as sacrosanct to establish and sustain democracy because expression is equivocated with participation in the political process. Illustrative of this point, the concept of "voice" refers to the opportunity to participate and is given significance as a procedural characteristic [@biggers2023, 157]. Thus, "equal political voice" is touted as both an ideal and a requisite [@jacobs2005]. 

> "Generations of Americans have worked to equalize citizen voice across lines of income, race, and gender. Today, however, the voices of American citizens are raised and heard unequally. The privileged participate more than others and are increasingly well organized to press their demands on government. Public officials, in turn, are much more responsive to the privileged than to average citizens and the less affluent. The voices of citizens with lower or moderate incomes are lost on the ears of inattentive
government officials, while the advantaged roar with a clarity and consistency that policymakers readily hear and routinely follow. The scourge of overt discrimination against African Americans and women has been replaced by a more subtle but potent threat—the growing concentration of the country’s wealth, income, and political influence in the hands of the few." [@jacobs2005, 1]

Unequal political voice means that government officials are responsive to those with voice and negligent of those without. The ideal, then, is to ensure that the potency of every voice is uniform among the populace. In other words, the ideal is that there is equal opportunity to participate in the political process among the populace, and the weight of that participation is equal across all participants. 

Yet there's a general awkwardness left over in that there's no clear way to discern the weight (effect) of popular political participation due to its general conflation with public opinion. As stated at the outset, public opinion is not necessary to the operation and production of government due to the fact that the maximum effect of public opinion is, simply, to *influence* the decisions and behavior of those who govern. The excerpts from both V.O. Key [-@key1961] and Almond and Verba [-@almond1963] referenced above are generally unobjectionable and illustrative of this understanding. However, political participation is defined by the same maximal effect the public can have through popular expression,

> "Political participation refers to those activities by private citizens that are more or less directly aimed at influencing the selection of governmental personnel and/or the actions they take" [@verba1972, 2]

What is explicitly clear is that public opinion doesn't make policy. It is, at best, influential upon the considerations of those who do make policy.  If the efficacy of public opinion is, at best, to influence the decisions and behaviors of government officials, and both the aim and effect of political participation is constrained to the efficacy of public opinion, then the efficacy of popular political participation is determined by the degree to which such participation influences government officials. However what is also implied is that popular political participation is entirely unnecessary to the operation of government. Reasonable people may disagree, but the extent to which such is the case appears untested. Is popular political participation necessary? If not, then the political system and operative government regime is undemocratic[^1]. 

[^1]: Oh but my elections--the saving grace.  

What is the maximum effect of the people's popular political activity? If the people's political activity is nothing more than the expression of public opinion, then in what sense can it be said that the people rule?   

> "To see that the popular will prevailed, they contrived no end of means to involve the people in the process of government. Not only were officials to be elected; they were to be subject to recall by the voters. Legislators, long subservient to special interests, were to find themselves subject to a popular veto through a referendum on their acts." [@key1961, 4]

This quote from V.O. Key is special. The means he describes to involve the people in the process of government are not simply expansion of political "voice" but result in substantial political consequence. Not only to elect, but the capacity of voters to recall those elected is simple but of paramount importance to the theory and actual practice of democracy. The capacity to recall an elected official being at the disposal of citizens is itself likely to influence the decisions and behavior of said officials. The mention of a popular veto through referendum may seem unconscionable today, but aligns with the notion that authority is delegated and not submitted to government agents.  


> ""Public opinion" in this discussion may simply be taken to mean those
opinions held by private persons which governments find it prudent to heed."
[@key1961, 14]

- From the excerpt by @jacobs2005, the ideal is to make or maximize government responsiveness. An ideally responsive government implies that "...the voices of American citizens are raised and heard" equally. Yet responsiveness is measured against an ideal--the degree to which government outcomes and policy appear equally influenced by those with the opportunity to participate in the political process.

- Definitions of democracy are then conveyed as "policy responsiveness to ordinary citizens" [@page2017, 5], where "ordinary citizens" is implied to refer to the majority of people in general and distinguished in contrast to minority groups of non-ordinary 'elites'. According to this and similar conceptions of democracy, the ills and inequalities of the political context and system are measured by the degree of unequal influence on the decisions and actions of government officials. 


- Policy congruence with public opinion takes on more significance as an indication of an unhealthy political system because it is suggestive of such unequal influence on government officials. The corrective is, then, to expand opportunity for expression with the aim of rendering government and politics more responsive [@page2017].

- The concept of representation insofar as it concerns representative government refers to the representation of interests of the people [@pitkin1967], and not mere deference to majority opinion. 


> "It follows that our problems can be more effectively addressed if we reform
our political system to achieve more democracy: more equal opportunity for all
citizens to shape what their government does and policies that better address
the needs of all Americans. If the political parties are democratized, for
example, so that each of them is forced to appeal more to the voters and less to
the party’s donors and activists, they will differ less sharply from each other.
That will reduce gridlock. Both parties will be more responsive to the citizenry
and more likely to adopt solutions that Americans favor for the problems we
face. Similarly, if we reform elections so that all citizens have an equal
voice, and if we mute the influence of political money and organized interests,
public officials will more faithfully reflect what ordinary Americans want.
Again, if the Congress and other political institutions are reformed to
represent all citizens equally, those institutions will be more harmonious— less
prone to clashes with each other that result in gridlock— and more responsive to
the citizenry as a whole." [@page2017, 4]

The ends sought is, repeatedly, to render governors more responsive, to ensure that government agents "...more faithfully reflect what ordinary Americans want", and to ensure that such agents would be, "...more likely to adopt solutions that Americans favor..." 


> "We define democracy as policy responsiveness to ordinary citizens— that is,
popular control of government. Or simply “majority rule.” This commonsense
definition reflects the foundation of our Constitution in the will of “we the
people of the United States.” It embodies the fundamental value of political
equality, insisting that in a democracy all citizens should have an equal
opportunity to influence the making of public policy. It reflects the assertion
in the Declaration of Independence that all men (we would now say all human
beings) are “created equal.” It corresponds to Abraham Lincoln’s espousal of
government “of the people, by the people, and for the people.”" [@page2017, 5]

Really rudimentary. 

However, what is overlooked is that designating the overarching point of political participation as "to influence" is not only what leads researchers to conflate political *influence* with political power, but also implies an underlying conception of democracy at base as well as the appropriate role citizens play according to that conception. In short, successfully imposing influence upon government officials is conflated with the power of government, leading to discussions and inquiries over who governs [@dahl1961; @jacobs2005; @kaylehmanschlozman2012; @page2017; @dimaggio2019] as well as fallacious and circular definitions on the concept of power [@dahl1957; @dahl1956; for review see @parietti2022]. Accordingly, democracy is conceived as a political system where in which there exists procedures for public participation in the political process, but the role of citizens is ultimately divested from agency and control of producing outcomes of said process. The role of citizens, then, is relegated to political participation where the ultimate aim is to successfully influence the decisions and behaviors of agents of government without a meaningful criteria for success. Similarly recognized by Almond and Verba's classic study on civic culture, the following excerpt is illustrative of this point.

> "Democracy is a political system in which ordinary citizens exercise control
over elites; and such control is legitimate, that is, supported by norms that
are accepted by elites and nonelites. In all societies, of course, the making of
specific decisions is concentrated in the hands of very few people. Neither the
ordinary citizen nor "public opinion" can make policy. If this is the case, the
problem of assessing the degree of democracy in a nation becomes one of
measuring the degree to which ordinary citizens control those who make the
significant decisions for a society---in most cases, governmental elites"
[@verba1965, 180]

Almond and Verba (1964) discussed how an individual or group may be considered politically influential, "it is only when officials act because they fear the consequences of not acting that a group may be considered to be politically influential and a participant in the decision".

In other words, successfully influencing politicians appears to have meant producing responsive government. Since successful influence is ascertained by whether the political official acted out of fear of consequence from not acting in the interests of some group. Almond and Verba (1964) characterized this as *political competence*, whereas the belief that one can exert such influence refers to an individual's *subjective competence*.

> "We shall roughly define the political influence of a group or individual over a governmental decision as equal to the degree to which governmental officials act to benefit that group or individual because the officials believe that they will risk some deprivation (they will risk their jobs, be criticized, lose votes) if they do not so act. Thus we define political influence in terms of both the outcome of the decision and the motives of the decision makers. The out come will benefit the influential groups or individuals more than it would if the influence were not exercised. And the decision makers act to benefit the groups or individuals because they believe they will suffer some deprivation or, what amounts to the same thing, fail to gain a reward. The latter criterion is important. Officials may act to benefit a particular group for a variety of reasons: out of a feeling of paternalism, for instance. But it is only when officials act because they fear the consequences of not acting that a group may be considered to be politically influential and a participant in the decision. If the individual can exert such influence, we shall consider him to be *politically competent*; or if he believes he can exert such influence, he will be *subjectively competent*." (Almond and Verba 1963, 180)

[Aside: We don't really have a clear objective measure of government responsiveness, nor a clear conception of it. Government responsiveness may mean congruence, to some extent, with public opinion. Other varieties may consider responsiveness in other ways. Ultimately, however, I have come to think that we struggle with this concept and measure, and many others, because we have distorted our understanding of democracy. In particular, we have somehow come to the belief that democracy is when the government responds and adheres to public opinion. When majority opinion or preference swings one way, and the government aligns itself with that opinion or preference, we have come to consider this to be democratic governance. Simple adherence to majority opinion in government decision or policy isn't a sufficient standard for democracy; An authoritarian may humor those subjected. An authoritarian (or few) may even be so benevolent as to enshrine rights to subjects and adhere to rule in respect of those rights. So when we've come to measure the health and quality of the political system, the regime, the country, we've assumed the burden is squarely on the public to meet certain requirements and hold government accountable for the sustainment of democracy. A competent public is one that effectively produces responsive government, and a responsive government is a democratic one. Further, a competent citizen is one that effectively influences agents of government, but this is confined to their competency to elect faithful representatives.]